// Testi della pagina Come funziona (/come-funziona) — l'admin li cambia da Admin → Testi.
// Nomi dei prodotti, prezzi, giorni e mesi non si scrivono qui: arrivano dal listino
// (data/catalogo.js) e dal semaforo (lib/semaforo.js) attraverso i segnaposto {…}.
// Anche i nomi e le spiegazioni dei colori del semaforo vengono da lib/semaforo.js.
export default {
    id: 'comeFunziona',
    nome: 'Come funziona',
    percorso: '/come-funziona',
    ordine: 40,
    testi: [
        { chiave: 'comeFunziona.meta.titolo', sezione: 'Motori di ricerca', etichetta: 'Titolo della scheda del browser', testo: 'Come funziona — CRIA' },
        { chiave: 'comeFunziona.meta.descrizione', sezione: 'Motori di ricerca', etichetta: 'Descrizione per i motori di ricerca', testo: "Come funziona CRIA: iscrizione e verifica dell'identità, il semaforo dell'inquilino, la segnalazione mensile, la contestazione, cosa succede se il canone non arriva e i quattro prodotti per il proprietario.", lungo: true },

        { chiave: 'comeFunziona.hero.occhiello', sezione: 'In alto', etichetta: 'Etichetta sopra il titolo', testo: 'Come funziona' },
        { chiave: 'comeFunziona.hero.titolo', sezione: 'In alto', etichetta: 'Titolo', testo: 'Un canone,\nun giorno del mese,\n*un semaforo.*' },
        { chiave: 'comeFunziona.hero.sottotitolo', sezione: 'In alto', etichetta: 'Sottotitolo', testo: "Dall'iscrizione alla segnalazione di ogni mese, da una contestazione a un canone non pagato: cosa succede, in che ordine e con quali tempi.", lungo: true },
        { chiave: 'comeFunziona.hero.indice1', sezione: 'In alto', etichetta: 'Indice · pulsante 1 (porta a «Per iniziare»)', testo: 'Per iniziare' },
        { chiave: 'comeFunziona.hero.indice2', sezione: 'In alto', etichetta: 'Indice · pulsante 2 (porta al semaforo)', testo: 'Il semaforo' },
        { chiave: 'comeFunziona.hero.indice3', sezione: 'In alto', etichetta: 'Indice · pulsante 3 (porta a «Ogni mese»)', testo: 'Il mese' },
        { chiave: 'comeFunziona.hero.indice4', sezione: 'In alto', etichetta: 'Indice · pulsante 4 (porta alla contestazione)', testo: 'La contestazione' },
        { chiave: 'comeFunziona.hero.indice5', sezione: 'In alto', etichetta: 'Indice · pulsante 5 (porta a «Se il canone non arriva»)', testo: 'Se non paga' },
        { chiave: 'comeFunziona.hero.indice6', sezione: 'In alto', etichetta: 'Indice · pulsante 6 (porta al confronto dei prodotti)', testo: 'I prodotti' },

        { chiave: 'comeFunziona.hero.meseInBreve.titolo', sezione: 'In alto · il mese in breve (esempio)', etichetta: 'Scritta in cima al riquadro', testo: 'Il mese in breve' },
        { chiave: 'comeFunziona.hero.meseInBreve.riga1.quando', sezione: 'In alto · il mese in breve (esempio)', etichetta: 'Riga 1 · quando', testo: 'Giorno {giorno}' },
        { chiave: 'comeFunziona.hero.meseInBreve.riga1.testo', sezione: 'In alto · il mese in breve (esempio)', etichetta: 'Riga 1 · cosa succede', testo: 'Scade il canone' },
        { chiave: 'comeFunziona.hero.meseInBreve.riga2.quando', sezione: 'In alto · il mese in breve (esempio)', etichetta: 'Riga 2 · quando', testo: '{numeroSolleciti} promemoria' },
        { chiave: 'comeFunziona.hero.meseInBreve.riga2.testo', sezione: 'In alto · il mese in breve (esempio)', etichetta: 'Riga 2 · cosa succede', testo: 'Per notifica, email e SMS' },
        { chiave: 'comeFunziona.hero.meseInBreve.riga3.quando', sezione: 'In alto · il mese in breve (esempio)', etichetta: 'Riga 3 · quando', testo: 'Entro {giorni} giorni' },
        { chiave: 'comeFunziona.hero.meseInBreve.riga3.testo', sezione: 'In alto · il mese in breve (esempio)', etichetta: 'Riga 3 · cosa succede', testo: 'Segnali il mancato pagamento: la copertura è attiva' },
        { chiave: 'comeFunziona.hero.meseInBreve.riga4.quando', sezione: 'In alto · il mese in breve (esempio)', etichetta: 'Riga 4 · quando', testo: 'Giorno {giorno}' },
        { chiave: 'comeFunziona.hero.meseInBreve.riga4.testo', sezione: 'In alto · il mese in breve (esempio)', etichetta: 'Riga 4 · cosa succede', testo: 'Nessuna segnalazione: il mese è non rilevato' },
        { chiave: 'comeFunziona.hero.domanda.testo', sezione: 'In alto · il mese in breve (esempio)', etichetta: 'Riquadro blu · domanda', testo: 'Il canone è arrivato?' },
        { chiave: 'comeFunziona.hero.domanda.si', sezione: 'In alto · il mese in breve (esempio)', etichetta: 'Riquadro blu · risposta sì', testo: 'Sì' },
        { chiave: 'comeFunziona.hero.domanda.no', sezione: 'In alto · il mese in breve (esempio)', etichetta: 'Riquadro blu · risposta no', testo: 'No' },

        { chiave: 'comeFunziona.perIniziare.occhiello', sezione: '01 · Per iniziare', etichetta: 'Occhiello', testo: 'Per iniziare' },
        { chiave: 'comeFunziona.perIniziare.titolo', sezione: '01 · Per iniziare', etichetta: 'Titolo', testo: 'Prima di tutto, *sappiamo chi sei.*' },
        { chiave: 'comeFunziona.perIniziare.intro', sezione: '01 · Per iniziare', etichetta: 'Testo sotto il titolo', testo: 'Un account verificato da una persona, un ruolo per ogni cappello che porti, e documenti che ognuno carica per sé.' },
        { chiave: 'comeFunziona.perIniziare.esempio.barra', sezione: '01 · Per iniziare', etichetta: 'Riquadro d’esempio · barra della finestra', testo: 'selettore di contesto' },
        { chiave: 'comeFunziona.perIniziare.esempio.occhiello', sezione: '01 · Per iniziare', etichetta: 'Riquadro d’esempio · occhiello', testo: 'Un account, due ruoli' },
        { chiave: 'comeFunziona.perIniziare.esempio.titolo', sezione: '01 · Per iniziare', etichetta: 'Riquadro d’esempio · domanda', testo: 'Come vuoi entrare?' },
        { chiave: 'comeFunziona.perIniziare.esempio.proprietario.titolo', sezione: '01 · Per iniziare', etichetta: 'Riquadro d’esempio · scelta 1', testo: 'Come proprietario' },
        { chiave: 'comeFunziona.perIniziare.esempio.proprietario.testo', sezione: '01 · Per iniziare', etichetta: 'Riquadro d’esempio · scelta 1, riga sotto', testo: 'I tuoi immobili e i loro contratti' },
        { chiave: 'comeFunziona.perIniziare.esempio.inquilino.titolo', sezione: '01 · Per iniziare', etichetta: 'Riquadro d’esempio · scelta 2', testo: 'Come inquilino' },
        { chiave: 'comeFunziona.perIniziare.esempio.inquilino.testo', sezione: '01 · Per iniziare', etichetta: 'Riquadro d’esempio · scelta 2, riga sotto', testo: 'Il tuo contratto e il tuo semaforo' },
        { chiave: 'comeFunziona.perIniziare.esempio.identita', sezione: '01 · Per iniziare', etichetta: 'Riquadro d’esempio · identità verificata', testo: 'Identità verificata da un operatore CRIA' },
        { chiave: 'comeFunziona.perIniziare.esempio.documenti', sezione: '01 · Per iniziare', etichetta: 'Riquadro d’esempio · titolo dell’elenco dei documenti', testo: 'Documenti del candidato' },
        { chiave: 'comeFunziona.perIniziare.esempio.documento1', sezione: '01 · Per iniziare', etichetta: 'Riquadro d’esempio · documento 1', testo: 'Documento d’identità' },
        { chiave: 'comeFunziona.perIniziare.esempio.caricato', sezione: '01 · Per iniziare', etichetta: 'Riquadro d’esempio · stato del documento caricato', testo: 'Caricato' },
        { chiave: 'comeFunziona.perIniziare.esempio.documento2', sezione: '01 · Per iniziare', etichetta: 'Riquadro d’esempio · documento 2', testo: 'Movimenti del canone · {mesi} mesi' },
        { chiave: 'comeFunziona.perIniziare.esempio.manca', sezione: '01 · Per iniziare', etichetta: 'Riquadro d’esempio · stato del documento mancante', testo: 'Manca' },
        { chiave: 'comeFunziona.perIniziare.esempio.nota', sezione: '01 · Per iniziare', etichetta: 'Riquadro d’esempio · nota in fondo', testo: 'Vedi cosa manca, non il contenuto dei documenti.' },
        { chiave: 'comeFunziona.perIniziare.passo1.titolo', sezione: '01 · Per iniziare', etichetta: 'Passo 1 · titolo', testo: 'Registrati' },
        { chiave: 'comeFunziona.perIniziare.passo1.testo', sezione: '01 · Per iniziare', etichetta: 'Passo 1 · testo', testo: 'Come persona fisica o come società. Puoi entrare anche con Google.' },
        { chiave: 'comeFunziona.perIniziare.passo2.titolo', sezione: '01 · Per iniziare', etichetta: 'Passo 2 · titolo', testo: 'Una persona verifica chi sei' },
        { chiave: 'comeFunziona.perIniziare.passo2.testo', sezione: '01 · Per iniziare', etichetta: 'Passo 2 · testo', testo: 'Carichi il documento d’identità e un operatore CRIA lo controlla. Vale anche se sei entrato con Google.' },
        { chiave: 'comeFunziona.perIniziare.passo3.titolo', sezione: '01 · Per iniziare', etichetta: 'Passo 3 · titolo', testo: 'Un account, più ruoli' },
        { chiave: 'comeFunziona.perIniziare.passo3.testo', sezione: '01 · Per iniziare', etichetta: 'Passo 3 · testo', testo: 'Lo stesso account può essere proprietario e inquilino: passi dall’uno all’altro con il selettore di contesto.' },
        { chiave: 'comeFunziona.perIniziare.passo4.titolo', sezione: '01 · Per iniziare', etichetta: 'Passo 4 · titolo', testo: 'Il prodotto sta sul contratto' },
        { chiave: 'comeFunziona.perIniziare.passo4.testo', sezione: '01 · Per iniziare', etichetta: 'Passo 4 · testo', testo: 'Con più immobili puoi scegliere un prodotto diverso per ciascuno. Il prezzo viene dal listino e dal canone che dichiari: non c’è un preventivo da chiedere né da aspettare.', lungo: true },
        { chiave: 'comeFunziona.perIniziare.passo5.titolo', sezione: '01 · Per iniziare', etichetta: 'Passo 5 · titolo', testo: 'Ognuno carica i propri documenti' },
        { chiave: 'comeFunziona.perIniziare.passo5.testo', sezione: '01 · Per iniziare', etichetta: 'Passo 5 · testo', testo: 'Il candidato inquilino carica i suoi da un link personale, con informativa e consenso: tu vedi quali documenti mancano, non i documenti. Dalla banca servono solo i movimenti del canone degli ultimi {mesi} mesi, non l’estratto conto intero.', lungo: true },
        { chiave: 'comeFunziona.perIniziare.passo6.titolo', sezione: '01 · Per iniziare', etichetta: 'Passo 6 · titolo', testo: 'Si firma in piattaforma' },
        { chiave: 'comeFunziona.perIniziare.passo6.testo', sezione: '01 · Per iniziare', etichetta: 'Passo 6 · testo', testo: 'Il contratto si firma elettronicamente dentro CRIA. CRIA non registra il contratto: ne riceve gli estremi di registrazione.', lungo: true },

        { chiave: 'comeFunziona.semaforo.occhiello', sezione: '02 · Il semaforo', etichetta: 'Occhiello', testo: 'Il semaforo' },
        { chiave: 'comeFunziona.semaforo.titolo', sezione: '02 · Il semaforo', etichetta: 'Titolo', testo: 'Non quanto paghi. *Quando paghi, in media.*' },
        { chiave: 'comeFunziona.semaforo.intro', sezione: '02 · Il semaforo', etichetta: 'Testo sotto il titolo (sotto, i quattro colori vengono dal semaforo)', testo: 'È la media del giorno del mese in cui il canone è stato pagato, negli ultimi {mesi} mesi. Niente punteggi: quattro risposte possibili.', lungo: true },
        { chiave: 'comeFunziona.semaforo.regola1.titolo', sezione: '02 · Il semaforo', etichetta: 'Regola 1 · titolo', testo: 'Si calcola sulla persona' },
        { chiave: 'comeFunziona.semaforo.regola1.testo', sezione: '02 · Il semaforo', etichetta: 'Regola 1 · testo', testo: 'Su tutti i suoi contratti di affitto, non su un contratto solo.' },
        { chiave: 'comeFunziona.semaforo.regola2.titolo', sezione: '02 · Il semaforo', etichetta: 'Regola 2 · titolo', testo: 'Un mese non rilevato pesa zero' },
        { chiave: 'comeFunziona.semaforo.regola2.testo', sezione: '02 · Il semaforo', etichetta: 'Regola 2 · testo', testo: 'Se nessuno lo segnala, non conta né a favore né contro.' },
        { chiave: 'comeFunziona.semaforo.regola3.titolo', sezione: '02 · Il semaforo', etichetta: 'Regola 3 · titolo', testo: 'Un mese contestato resta fuori' },
        { chiave: 'comeFunziona.semaforo.regola3.testo', sezione: '02 · Il semaforo', etichetta: 'Regola 3 · testo', testo: 'Finché la contestazione non si chiude.' },
        { chiave: 'comeFunziona.semaforo.regola4.titolo', sezione: '02 · Il semaforo', etichetta: 'Regola 4 · titolo', testo: 'L’inquilino lo vede sempre' },
        { chiave: 'comeFunziona.semaforo.regola4.testo', sezione: '02 · Il semaforo', etichetta: 'Regola 4 · testo', testo: 'Il proprio semaforo, con la spiegazione di come è costruito.' },
        { chiave: 'comeFunziona.semaforo.regola5.titolo', sezione: '02 · Il semaforo', etichetta: 'Regola 5 · titolo', testo: 'Nessuno lo cambia a mano' },
        { chiave: 'comeFunziona.semaforo.regola5.testo', sezione: '02 · Il semaforo', etichetta: 'Regola 5 · testo', testo: 'Nemmeno in CRIA. Solo una contestazione istruita può correggerlo.' },
        { chiave: 'comeFunziona.semaforo.esempio.barra', sezione: '02 · Il semaforo', etichetta: 'Riquadro d’esempio · barra della finestra', testo: 'il mio semaforo' },
        { chiave: 'comeFunziona.semaforo.esempio.occhiello', sezione: '02 · Il semaforo', etichetta: 'Riquadro d’esempio · occhiello', testo: 'Ultimi {mesi} mesi · tutti i tuoi contratti' },
        { chiave: 'comeFunziona.semaforo.esempio.titolo', sezione: '02 · Il semaforo', etichetta: 'Riquadro d’esempio · titolo', testo: 'Come è costruito il tuo semaforo' },
        { chiave: 'comeFunziona.semaforo.esempio.giornoMedio', sezione: '02 · Il semaforo', etichetta: 'Riquadro d’esempio · riga sotto il colore', testo: 'Giorno medio di pagamento: {media}' },
        { chiave: 'comeFunziona.semaforo.esempio.inizialiMesi', sezione: '02 · Il semaforo', etichetta: 'Riquadro d’esempio · iniziali dei mesi, da gennaio a dicembre, separate da uno spazio', testo: 'G F M A M G L A S O N D' },
        { chiave: 'comeFunziona.semaforo.esempio.rilevati', sezione: '02 · Il semaforo', etichetta: 'Riquadro d’esempio · legenda 1', testo: '{numero} mesi rilevati: contano' },
        { chiave: 'comeFunziona.semaforo.esempio.nonRilevati', sezione: '02 · Il semaforo', etichetta: 'Riquadro d’esempio · legenda 2', testo: '{numero} non rilevato: pesa zero' },
        { chiave: 'comeFunziona.semaforo.esempio.contestati', sezione: '02 · Il semaforo', etichetta: 'Riquadro d’esempio · legenda 3', testo: '{numero} contestato: fuori finché non si chiude' },

        { chiave: 'comeFunziona.mese.occhiello', sezione: '03 · Ogni mese', etichetta: 'Occhiello', testo: 'Ogni mese' },
        { chiave: 'comeFunziona.mese.titolo', sezione: '03 · Ogni mese', etichetta: 'Titolo', testo: 'Il canone è arrivato? *Sì o no.*' },
        { chiave: 'comeFunziona.mese.intro', sezione: '03 · Ogni mese', etichetta: 'Testo sotto il titolo', testo: 'Prima che la finestra si chiuda ricevi {numeroSolleciti} promemoria, con una sola domanda. Se il canone è arrivato rispondi sì, e il mese entra nel semaforo con il giorno del pagamento.', lungo: true },
        { chiave: 'comeFunziona.mese.tappa1.quando', sezione: '03 · Ogni mese', etichetta: 'Tappa 1 · quando', testo: 'Giorno {giorno}' },
        { chiave: 'comeFunziona.mese.tappa1.testo', sezione: '03 · Ogni mese', etichetta: 'Tappa 1 · testo', testo: 'Scade il canone.' },
        { chiave: 'comeFunziona.mese.tappa2.quando', sezione: '03 · Ogni mese', etichetta: 'Tappa 2 · quando', testo: '{numeroSolleciti} promemoria' },
        { chiave: 'comeFunziona.mese.tappa2.testo', sezione: '03 · Ogni mese', etichetta: 'Tappa 2 · testo ({solleciti} è l’elenco dei promemoria del listino)', testo: '{solleciti}. Per notifica, email e SMS.' },
        { chiave: 'comeFunziona.mese.tappa3.quando', sezione: '03 · Ogni mese', etichetta: 'Tappa 3 · quando', testo: 'Entro {giorni} giorni' },
        { chiave: 'comeFunziona.mese.tappa3.testo', sezione: '03 · Ogni mese', etichetta: 'Tappa 3 · testo', testo: 'Di calendario dalla scadenza: la finestra per segnalare il mancato pagamento con la copertura attiva.' },
        { chiave: 'comeFunziona.mese.tappa4.quando', sezione: '03 · Ogni mese', etichetta: 'Tappa 4 · quando', testo: 'Giorno {giorno}' },
        { chiave: 'comeFunziona.mese.tappa4.testo', sezione: '03 · Ogni mese', etichetta: 'Tappa 4 · testo', testo: 'Il mese si chiude. Senza nessuna segnalazione diventa non rilevato.' },
        { chiave: 'comeFunziona.mese.esiti.occhiello', sezione: '03 · Ogni mese', etichetta: 'Riquadro dei tre esiti · occhiello', testo: 'Se il canone non è arrivato' },
        { chiave: 'comeFunziona.mese.esiti.titolo', sezione: '03 · Ogni mese', etichetta: 'Riquadro dei tre esiti · titolo', testo: 'Tre esiti, *e contano i tempi*' },
        { chiave: 'comeFunziona.mese.esiti.voceSemaforo', sezione: '03 · Ogni mese', etichetta: 'Riquadro dei tre esiti · voce «Semaforo» in ogni scheda', testo: 'Semaforo' },
        { chiave: 'comeFunziona.mese.esiti.voceCopertura', sezione: '03 · Ogni mese', etichetta: 'Riquadro dei tre esiti · voce «Copertura» in ogni scheda', testo: 'Copertura' },
        { chiave: 'comeFunziona.mese.esito1.titolo', sezione: '03 · Ogni mese', etichetta: 'Esito 1 · titolo', testo: 'Lo segnali entro {giorni} giorni' },
        { chiave: 'comeFunziona.mese.esito1.semaforo', sezione: '03 · Ogni mese', etichetta: 'Esito 1 · semaforo', testo: 'Il mese conta come non pagato.' },
        { chiave: 'comeFunziona.mese.esito1.copertura', sezione: '03 · Ogni mese', etichetta: 'Esito 1 · copertura', testo: 'Attiva. La pratica di morosità parte subito.' },
        { chiave: 'comeFunziona.mese.esito2.titolo', sezione: '03 · Ogni mese', etichetta: 'Esito 2 · titolo', testo: 'Lo segnali dopo {giorni} giorni' },
        { chiave: 'comeFunziona.mese.esito2.semaforo', sezione: '03 · Ogni mese', etichetta: 'Esito 2 · semaforo', testo: 'Il mese conta comunque come non pagato: per l’inquilino è la verità.' },
        { chiave: 'comeFunziona.mese.esito2.copertura', sezione: '03 · Ogni mese', etichetta: 'Esito 2 · copertura', testo: 'Decade per quel mese.' },
        { chiave: 'comeFunziona.mese.esito3.titolo', sezione: '03 · Ogni mese', etichetta: 'Esito 3 · titolo', testo: 'Entro il giorno {giorno} nessuno segnala' },
        { chiave: 'comeFunziona.mese.esito3.semaforo', sezione: '03 · Ogni mese', etichetta: 'Esito 3 · semaforo', testo: 'Il mese è non rilevato: non conta.' },
        { chiave: 'comeFunziona.mese.esito3.copertura', sezione: '03 · Ogni mese', etichetta: 'Esito 3 · copertura', testo: 'Nessuna per quel mese.' },
        { chiave: 'comeFunziona.mese.esiti.nota1', sezione: '03 · Ogni mese', etichetta: 'Sotto le schede · nota 1', testo: '**La copertura riprende** dal primo mese segnalato correttamente.' },
        { chiave: 'comeFunziona.mese.esiti.nota2', sezione: '03 · Ogni mese', etichetta: 'Sotto le schede · nota 2 (il prodotto in cui incassa CRIA)', testo: '**{nomeProdotto}:** incassa CRIA, che sa già se il canone è arrivato. Non devi segnalare nulla.' },
        { chiave: 'comeFunziona.mese.esiti.nota3', sezione: '03 · Ogni mese', etichetta: 'Sotto le schede · nota 3 (il prodotto senza garanzia)', testo: '**{nomeProdotto}:** non c’è copertura. La segnalazione vale per il semaforo dell’inquilino.' },

        { chiave: 'comeFunziona.contestazione.occhiello', sezione: '04 · La contestazione', etichetta: 'Occhiello', testo: 'La contestazione' },
        { chiave: 'comeFunziona.contestazione.titolo', sezione: '04 · La contestazione', etichetta: 'Titolo', testo: 'Una segnalazione sbagliata *si contesta con le prove.*' },
        { chiave: 'comeFunziona.contestazione.intro', sezione: '04 · La contestazione', etichetta: 'Testo sotto il titolo', testo: 'È l’unico modo per correggere un semaforo: nessuno in CRIA può cambiarlo a mano.' },
        { chiave: 'comeFunziona.contestazione.passo1.titolo', sezione: '04 · La contestazione', etichetta: 'Passo 1 · titolo', testo: 'Chi' },
        { chiave: 'comeFunziona.contestazione.passo1.testo', sezione: '04 · La contestazione', etichetta: 'Passo 1 · testo', testo: 'Solo l’inquilino.' },
        { chiave: 'comeFunziona.contestazione.passo2.titolo', sezione: '04 · La contestazione', etichetta: 'Passo 2 · titolo', testo: 'Su cosa' },
        { chiave: 'comeFunziona.contestazione.passo2.testo', sezione: '04 · La contestazione', etichetta: 'Passo 2 · testo', testo: 'Solo su una segnalazione di canone non pagato.' },
        { chiave: 'comeFunziona.contestazione.passo3.titolo', sezione: '04 · La contestazione', etichetta: 'Passo 3 · titolo', testo: 'Entro quando' },
        { chiave: 'comeFunziona.contestazione.passo3.testo', sezione: '04 · La contestazione', etichetta: 'Passo 3 · testo', testo: 'Entro {giorni} giorni dalla segnalazione.' },
        { chiave: 'comeFunziona.contestazione.passo4.titolo', sezione: '04 · La contestazione', etichetta: 'Passo 4 · titolo', testo: 'Con cosa' },
        { chiave: 'comeFunziona.contestazione.passo4.testo', sezione: '04 · La contestazione', etichetta: 'Passo 4 · testo', testo: 'Con una prova: per esempio la ricevuta del bonifico.' },
        { chiave: 'comeFunziona.contestazione.passo5.titolo', sezione: '04 · La contestazione', etichetta: 'Passo 5 · titolo', testo: 'Chi decide' },
        { chiave: 'comeFunziona.contestazione.passo5.testo', sezione: '04 · La contestazione', etichetta: 'Passo 5 · testo', testo: 'CRIA, sulle prove di entrambe le parti. Risponde entro {giorni} giorni, e finché la contestazione è aperta il mese non conta nel semaforo.', lungo: true },
        { chiave: 'comeFunziona.contestazione.esempio.barra', sezione: '04 · La contestazione', etichetta: 'Riquadro d’esempio · barra della finestra', testo: 'contestazione' },
        { chiave: 'comeFunziona.contestazione.esempio.occhiello', sezione: '04 · La contestazione', etichetta: 'Riquadro d’esempio · occhiello (accanto, lo stato viene dal semaforo)', testo: 'Segnalazione · luglio' },
        { chiave: 'comeFunziona.contestazione.esempio.titolo', sezione: '04 · La contestazione', etichetta: 'Riquadro d’esempio · segnalazione contestata', testo: '«Canone non pagato»' },
        { chiave: 'comeFunziona.contestazione.esempio.tuaContestazione', sezione: '04 · La contestazione', etichetta: 'Riquadro d’esempio · titolo del messaggio', testo: 'La tua contestazione' },
        { chiave: 'comeFunziona.contestazione.esempio.messaggio', sezione: '04 · La contestazione', etichetta: 'Riquadro d’esempio · messaggio dell’inquilino', testo: 'Il canone è stato pagato con bonifico: allego la ricevuta.' },
        { chiave: 'comeFunziona.contestazione.esempio.allegato', sezione: '04 · La contestazione', etichetta: 'Riquadro d’esempio · file allegato', testo: 'ricevuta-bonifico.pdf' },
        { chiave: 'comeFunziona.contestazione.esempio.meseFuori', sezione: '04 · La contestazione', etichetta: 'Riquadro d’esempio · riga 1 in fondo', testo: 'Il mese non conta nel semaforo finché la contestazione è aperta' },
        { chiave: 'comeFunziona.contestazione.esempio.decisione', sezione: '04 · La contestazione', etichetta: 'Riquadro d’esempio · riga 2 in fondo', testo: 'CRIA decide sulle prove di entrambe le parti, entro {giorni} giorni' },

        { chiave: 'comeFunziona.seNonPaga.occhiello', sezione: '05 · Se il canone non arriva', etichetta: 'Occhiello', testo: 'Se il canone non arriva' },
        { chiave: 'comeFunziona.seNonPaga.titolo', sezione: '05 · Se il canone non arriva', etichetta: 'Titolo', testo: 'Il canone non arriva? *La pratica parte.*' },
        { chiave: 'comeFunziona.seNonPaga.intro', sezione: '05 · Se il canone non arriva', etichetta: 'Testo sotto il titolo ({prodottiConGaranzia} sono i prodotti con garanzia del listino)', testo: 'Con {prodottiConGaranzia}, ecco cosa succede quando un canone non viene pagato.' },
        { chiave: 'comeFunziona.seNonPaga.passo1.titolo', sezione: '05 · Se il canone non arriva', etichetta: 'Scheda 1 · titolo', testo: 'Si apre la pratica di morosità' },
        { chiave: 'comeFunziona.seNonPaga.passo1.testo', sezione: '05 · Se il canone non arriva', etichetta: 'Scheda 1 · testo', testo: 'Subito, se il mancato pagamento è segnalato entro {giorni} giorni dalla scadenza.' },
        { chiave: 'comeFunziona.seNonPaga.passo2.titolo', sezione: '05 · Se il canone non arriva', etichetta: 'Scheda 2 · titolo', testo: 'Parte il recupero' },
        { chiave: 'comeFunziona.seNonPaga.passo2.testo', sezione: '05 · Se il canone non arriva', etichetta: 'Scheda 2 · testo', testo: 'Prima un piano di rientro con l’inquilino. Se serve, l’avvocato.' },
        { chiave: 'comeFunziona.seNonPaga.passo3.titolo', sezione: '05 · Se il canone non arriva', etichetta: 'Scheda 3 · titolo', testo: 'Con la garanzia, CRIA ti indennizza' },
        { chiave: 'comeFunziona.seNonPaga.passo3.testo', sezione: '05 · Se il canone non arriva', etichetta: 'Scheda 3 · testo', testo: 'Ogni prodotto con garanzia ha la sua franchigia: la trovi nel confronto qui sotto.' },
        { chiave: 'comeFunziona.seNonPaga.senzaCopertura.occhiello', sezione: '05 · Se il canone non arriva', etichetta: 'Riquadro in fondo · occhiello', testo: 'Anche senza copertura' },
        { chiave: 'comeFunziona.seNonPaga.senzaCopertura.titolo', sezione: '05 · Se il canone non arriva', etichetta: 'Riquadro in fondo · titolo', testo: 'Non coperto *non vuol dire non gestito.*' },
        { chiave: 'comeFunziona.seNonPaga.senzaCopertura.testo', sezione: '05 · Se il canone non arriva', etichetta: 'Riquadro in fondo · testo', testo: 'Se la copertura di un mese è decaduta, la pratica di morosità si apre lo stesso e il recupero parte. La copertura riprende dal primo mese segnalato correttamente.', lungo: true },
        { chiave: 'comeFunziona.seNonPaga.senzaCopertura.nota', sezione: '05 · Se il canone non arriva', etichetta: 'Riquadro in fondo · nota (il prodotto senza garanzia)', testo: '**{nomeProdotto}** non ha garanzia: nessun indennizzo. Il mancato pagamento vale per il semaforo dell’inquilino.' },

        { chiave: 'comeFunziona.prodotti.occhiello', sezione: '06 · I prodotti a confronto', etichetta: 'Occhiello', testo: 'Per il proprietario' },
        { chiave: 'comeFunziona.prodotti.titolo', sezione: '06 · I prodotti a confronto', etichetta: 'Titolo', testo: 'Quattro prodotti *a confronto.*' },
        { chiave: 'comeFunziona.prodotti.intro', sezione: '06 · I prodotti a confronto', etichetta: 'Testo sotto il titolo', testo: 'Il prodotto sta sul contratto: con più immobili puoi usarne di diversi. Il prezzo viene dal listino e dal canone che dichiari, senza preventivo.', lungo: true },
        { chiave: 'comeFunziona.prodotti.tabella.prodotto', sezione: '06 · I prodotti a confronto', etichetta: 'Tabella · intestazione della prima colonna (nomi e prezzi vengono dal listino)', testo: 'Prodotto' },
        { chiave: 'comeFunziona.prodotti.tabella.prezzo', sezione: '06 · I prodotti a confronto', etichetta: 'Tabella · riga «Prezzo»', testo: 'Prezzo' },
        { chiave: 'comeFunziona.prodotti.tabella.garanzia', sezione: '06 · I prodotti a confronto', etichetta: 'Tabella · riga «Garanzia»', testo: 'Garanzia' },
        { chiave: 'comeFunziona.prodotti.tabella.garanziaSi', sezione: '06 · I prodotti a confronto', etichetta: 'Tabella · garanzia · prodotto con garanzia', testo: 'Sì' },
        { chiave: 'comeFunziona.prodotti.tabella.garanziaNo', sezione: '06 · I prodotti a confronto', etichetta: 'Tabella · garanzia · prodotto senza garanzia', testo: 'No' },
        { chiave: 'comeFunziona.prodotti.tabella.franchigia', sezione: '06 · I prodotti a confronto', etichetta: 'Tabella · riga «Franchigia»', testo: 'Franchigia' },
        { chiave: 'comeFunziona.prodotti.tabella.franchigiaUnMese', sezione: '06 · I prodotti a confronto', etichetta: 'Tabella · franchigia di un mese', testo: '{mesi} mese' },
        { chiave: 'comeFunziona.prodotti.tabella.franchigiaMesi', sezione: '06 · I prodotti a confronto', etichetta: 'Tabella · franchigia di più mesi', testo: '{mesi} mesi' },
        { chiave: 'comeFunziona.prodotti.tabella.franchigiaNessuna', sezione: '06 · I prodotti a confronto', etichetta: 'Tabella · franchigia · prodotto senza garanzia', testo: '—' },
        { chiave: 'comeFunziona.prodotti.tabella.chiIncassa', sezione: '06 · I prodotti a confronto', etichetta: 'Tabella · riga «Chi incassa il canone»', testo: 'Chi incassa il canone' },
        { chiave: 'comeFunziona.prodotti.tabella.incassaCria', sezione: '06 · I prodotti a confronto', etichetta: 'Tabella · chi incassa · incassa CRIA', testo: 'CRIA, e lo bonifica a te' },
        { chiave: 'comeFunziona.prodotti.tabella.incassaTu', sezione: '06 · I prodotti a confronto', etichetta: 'Tabella · chi incassa · incassa il proprietario', testo: 'Tu' },
        { chiave: 'comeFunziona.prodotti.tabella.segnalazione', sezione: '06 · I prodotti a confronto', etichetta: 'Tabella · riga «Segnalazione mensile»', testo: 'Segnalazione mensile' },
        { chiave: 'comeFunziona.prodotti.tabella.segnalazioneCria', sezione: '06 · I prodotti a confronto', etichetta: 'Tabella · segnalazione · incassa CRIA', testo: 'Nessuna: CRIA sa già' },
        { chiave: 'comeFunziona.prodotti.tabella.segnalazioneTu', sezione: '06 · I prodotti a confronto', etichetta: 'Tabella · segnalazione · incassa il proprietario', testo: 'Tu: sì o no, ogni mese' },
        { chiave: 'comeFunziona.prodotti.tabella.semaforo', sezione: '06 · I prodotti a confronto', etichetta: 'Tabella · riga «Semaforo dell’inquilino»', testo: 'Semaforo dell’inquilino' },
        { chiave: 'comeFunziona.prodotti.tabella.semaforoSi', sezione: '06 · I prodotti a confronto', etichetta: 'Tabella · semaforo dell’inquilino · tutti i prodotti', testo: 'Si aggiorna' },
        { chiave: 'comeFunziona.prodotti.tabella.inBreve', sezione: '06 · I prodotti a confronto', etichetta: 'Tabella · ultima riga (le descrizioni vengono dal listino)', testo: 'In breve' },

        { chiave: 'comeFunziona.chiusura.occhiello', sezione: 'Chiusura', etichetta: 'Occhiello', testo: 'Da dove parti?' },
        { chiave: 'comeFunziona.chiusura.titolo', sezione: 'Chiusura', etichetta: 'Titolo', testo: 'Quattro porte, *un solo semaforo.*' },
        { chiave: 'comeFunziona.chiusura.porta1.chi', sezione: 'Chiusura', etichetta: 'Porta 1 · per chi', testo: 'Proprietario' },
        { chiave: 'comeFunziona.chiusura.porta1.titolo', sezione: 'Chiusura', etichetta: 'Porta 1 · titolo', testo: 'Vuoi coprirti su un contratto' },
        { chiave: 'comeFunziona.chiusura.porta1.testo', sezione: 'Chiusura', etichetta: 'Porta 1 · testo', testo: 'Gestione, Completo o Segnalazione, dal listino.' },
        { chiave: 'comeFunziona.chiusura.porta2.chi', sezione: 'Chiusura', etichetta: 'Porta 2 · per chi', testo: 'Proprietario' },
        { chiave: 'comeFunziona.chiusura.porta2.titolo', sezione: 'Chiusura', etichetta: 'Porta 2 · titolo', testo: 'Stai valutando un candidato' },
        { chiave: 'comeFunziona.chiusura.porta2.testo', sezione: 'Chiusura', etichetta: 'Porta 2 · testo', testo: '{nomeProdotto} · {prezzo}. Risultato entro {ore} ore, in piattaforma.' },
        { chiave: 'comeFunziona.chiusura.porta3.chi', sezione: 'Chiusura', etichetta: 'Porta 3 · per chi', testo: 'Inquilino' },
        { chiave: 'comeFunziona.chiusura.porta3.titolo', sezione: 'Chiusura', etichetta: 'Porta 3 · titolo', testo: 'Vuoi il tuo certificato' },
        { chiave: 'comeFunziona.chiusura.porta3.testo', sezione: 'Chiusura', etichetta: 'Porta 3 · testo', testo: 'Gratuito con un contratto CRIA attivo, {prezzo} su autocandidatura. Vedere i tuoi dati è sempre gratuito (art. 15 GDPR).' },
        { chiave: 'comeFunziona.chiusura.porta4.chi', sezione: 'Chiusura', etichetta: 'Porta 4 · per chi', testo: 'Agenzia immobiliare' },
        { chiave: 'comeFunziona.chiusura.porta4.titolo', sezione: 'Chiusura', etichetta: 'Porta 4 · titolo', testo: 'Selezioni candidati per i tuoi annunci' },
        { chiave: 'comeFunziona.chiusura.porta4.testo', sezione: 'Chiusura', etichetta: 'Porta 4 · testo', testo: '{nomeProdotto} · {prezzo}. Scrivici.' },
        { chiave: 'comeFunziona.chiusura.pulsante', sezione: 'Chiusura', etichetta: 'Pulsante verso le domande frequenti', testo: 'Hai altre domande? Leggi le FAQ' },
    ],
};
