// Testi della home (/) — pages/Vetrina/HomePage.jsx. L'admin li cambia da Testi.
// Nomi dei prodotti, prezzi, giorni e mesi arrivano dal listino e dalle regole del
// semaforo: nei testi sono segnaposto. Dove la pagina scrive «5 giorni» o «1 mese»
// per intero, il segnaposto {giorni} o {mesi} contiene anche la parola.
export default {
    id: 'home',
    nome: 'Home',
    percorso: '/',
    ordine: 10,
    testi: [
        { chiave: 'home.meta.titolo', sezione: 'Scheda del browser e motori di ricerca', etichetta: 'Titolo della scheda', testo: 'CRIA — Centrale Rischi Immobiliare Affitti' },
        { chiave: 'home.meta.descrizione', sezione: 'Scheda del browser e motori di ricerca', etichetta: 'Descrizione per i motori di ricerca', testo: "CRIA, Centrale Rischi Immobiliare Affitti: il semaforo dei pagamenti dell'affitto, calcolato sulla persona. {nomeProdotto} per chi sta per affittare, il certificato per gli inquilini, i prodotti per i proprietari.", lungo: true },

        // ─── In alto ───
        { chiave: 'home.hero.occhiello', sezione: 'In alto', etichetta: 'Scritta nel riquadro sopra il titolo', testo: 'Centrale Rischi Immobiliare Affitti' },
        { chiave: 'home.hero.titolo', sezione: 'In alto', etichetta: 'Titolo', testo: "Lo storico dell'affitto, *in un semaforo*." },
        { chiave: 'home.hero.sottotitolo', sezione: 'In alto', etichetta: 'Sottotitolo', testo: "CRIA registra ogni mese se il canone è stato pagato, e in che giorno. Da lì nasce il semaforo di chi è in affitto: calcolato sulla persona, su tutti i suoi contratti, e sempre visibile all'inquilino stesso.", lungo: true },
        { chiave: 'home.hero.pulsanteProprietario', sezione: 'In alto', etichetta: 'Pulsante per i proprietari', testo: 'Sono un proprietario' },
        { chiave: 'home.hero.pulsanteInquilino', sezione: 'In alto', etichetta: 'Pulsante per gli inquilini', testo: 'Sono un inquilino' },
        { chiave: 'home.hero.verifica.domanda', sezione: 'In alto', etichetta: 'Frase prima del link alla verifica', testo: 'Stai per affittare a qualcuno?' },
        { chiave: 'home.hero.verifica.link', sezione: 'In alto', etichetta: 'Link alla verifica', testo: 'Verifica il candidato con {nomeProdotto}' },
        { chiave: 'home.hero.regola1.testo', sezione: 'In alto · tre numeri', etichetta: 'Numero 1 · testo sotto i giorni', testo: 'per segnalare un mancato pagamento con la copertura attiva' },
        { chiave: 'home.hero.regola2.numero', sezione: 'In alto · tre numeri', etichetta: 'Numero 2 · il numero', testo: '{ore} ore' },
        { chiave: 'home.hero.regola2.testo', sezione: 'In alto · tre numeri', etichetta: 'Numero 2 · testo sotto', testo: "per l'esito di {nomeProdotto}" },
        { chiave: 'home.hero.regola3.testo', sezione: 'In alto · tre numeri', etichetta: 'Numero 3 · testo sotto i mesi', testo: 'di validità del certificato inquilino' },

        { chiave: 'home.hero.mockup.finestra', sezione: 'In alto · semaforo d’esempio', etichetta: 'Barra della finestra', testo: 'Area inquilino' },
        { chiave: 'home.hero.mockup.titolo', sezione: 'In alto · semaforo d’esempio', etichetta: 'Titoletto', testo: 'Il mio semaforo · ultimi {mesi} mesi' },
        { chiave: 'home.hero.mockup.spiegazione', sezione: 'In alto · semaforo d’esempio', etichetta: 'Riga sotto il colore ({spiegazione} viene dal semaforo)', testo: '{spiegazione} · calcolato su tutti i tuoi contratti' },
        { chiave: 'home.hero.mockup.giornoMedio', sezione: 'In alto · semaforo d’esempio', etichetta: 'Riquadro a sinistra', testo: 'Giorno medio' },
        { chiave: 'home.hero.mockup.nonRilevati', sezione: 'In alto · semaforo d’esempio', etichetta: 'Riquadro a destra', testo: 'Non rilevati' },
        { chiave: 'home.hero.mockup.pesoZero', sezione: 'In alto · semaforo d’esempio', etichetta: 'Riquadro a destra · accanto al numero', testo: '· peso zero' },
        { chiave: 'home.hero.mockup.promemoria.etichetta', sezione: 'In alto · semaforo d’esempio', etichetta: 'Promemoria blu · titoletto', testo: 'Promemoria al proprietario' },
        { chiave: 'home.hero.mockup.promemoria.domanda', sezione: 'In alto · semaforo d’esempio', etichetta: 'Promemoria blu · domanda', testo: 'Il canone è arrivato?' },
        { chiave: 'home.hero.mockup.promemoria.si', sezione: 'In alto · semaforo d’esempio', etichetta: 'Promemoria blu · risposta sì', testo: 'Sì' },
        { chiave: 'home.hero.mockup.promemoria.no', sezione: 'In alto · semaforo d’esempio', etichetta: 'Promemoria blu · risposta no', testo: 'No' },
        { chiave: 'home.hero.mockup.bloccato.titolo', sezione: 'In alto · semaforo d’esempio', etichetta: 'Etichetta col lucchetto · titolo', testo: 'Nessuno lo cambia a mano' },
        { chiave: 'home.hero.mockup.bloccato.testo', sezione: 'In alto · semaforo d’esempio', etichetta: 'Etichetta col lucchetto · riga sotto', testo: 'lo corregge solo una contestazione' },
        { chiave: 'home.hero.scopriDiPiu', sezione: 'In alto', etichetta: 'Invito a scorrere, in fondo', testo: 'Scopri di più' },

        // ─── Il semaforo ───
        { chiave: 'home.semaforo.occhiello', sezione: 'Il semaforo', etichetta: 'Occhiello', testo: 'Il semaforo' },
        { chiave: 'home.semaforo.titolo', sezione: 'Il semaforo', etichetta: 'Titolo · seconda riga (la prima sono i nomi dei tre colori, che vengono dal semaforo)', testo: '*E se i dati non bastano, nessun colore.*' },
        { chiave: 'home.semaforo.testo', sezione: 'Il semaforo', etichetta: 'Testo', testo: "Il semaforo è la media del giorno del mese in cui è stato pagato il canone, sugli ultimi {mesi} mesi. Si calcola sulla persona, mettendo insieme tutti i suoi contratti d'affitto, non sul singolo contratto.", lungo: true },
        { chiave: 'home.semaforo.principio1', sezione: 'Il semaforo', etichetta: 'Principio 1', testo: "L'inquilino vede sempre il proprio semaforo, con la spiegazione di come è costruito." },
        { chiave: 'home.semaforo.principio2', sezione: 'Il semaforo', etichetta: 'Principio 2', testo: 'Un mese che nessuno ha segnalato è «non rilevato»: pesa zero, né a favore né contro.' },
        { chiave: 'home.semaforo.principio3', sezione: 'Il semaforo', etichetta: 'Principio 3', testo: 'Un mese contestato resta fuori dal calcolo finché la contestazione non si chiude.' },
        { chiave: 'home.semaforo.principio4', sezione: 'Il semaforo', etichetta: 'Principio 4', testo: 'Nessuno in CRIA può cambiare un semaforo a mano: lo corregge solo una contestazione istruita.' },
        { chiave: 'home.semaforo.tag.verde', sezione: 'Il semaforo · i quattro esiti', etichetta: 'Etichetta colorata del verde', testo: 'Verde' },
        { chiave: 'home.semaforo.tag.giallo', sezione: 'Il semaforo · i quattro esiti', etichetta: 'Etichetta colorata del giallo', testo: 'Giallo' },
        { chiave: 'home.semaforo.tag.rosso', sezione: 'Il semaforo · i quattro esiti', etichetta: 'Etichetta colorata del rosso', testo: 'Rosso' },
        { chiave: 'home.semaforo.tag.nessunColore', sezione: 'Il semaforo · i quattro esiti', etichetta: 'Etichetta dello storico insufficiente', testo: 'Nessun colore' },

        // ─── Da dove entri ───
        { chiave: 'home.porte.occhiello', sezione: 'Da dove entri', etichetta: 'Occhiello', testo: 'Da dove entri' },
        { chiave: 'home.porte.titolo', sezione: 'Da dove entri', etichetta: 'Titolo', testo: 'Quattro domande, *quattro porte.*' },
        { chiave: 'home.porte.sottotitolo', sezione: 'Da dove entri', etichetta: 'Sottotitolo', testo: 'Chi arriva su CRIA ha una domanda precisa. Ognuna ha il suo percorso e il suo prezzo.' },
        { chiave: 'home.porte.porta1.chi', sezione: 'Da dove entri · porta 1', etichetta: 'Per chi (testo e prezzo vengono dal listino)', testo: 'Proprietario che valuta un candidato' },
        { chiave: 'home.porte.porta1.domanda', sezione: 'Da dove entri · porta 1', etichetta: 'Domanda', testo: '«Questa persona paga?»' },
        { chiave: 'home.porte.porta1.pulsante', sezione: 'Da dove entri · porta 1', etichetta: 'Link in fondo', testo: 'Verifica un candidato' },
        { chiave: 'home.porte.porta2.chi', sezione: 'Da dove entri · porta 2', etichetta: 'Per chi', testo: 'Inquilino che vuole il proprio certificato' },
        { chiave: 'home.porte.porta2.domanda', sezione: 'Da dove entri · porta 2', etichetta: 'Domanda', testo: '«Come dimostro che pago?»' },
        { chiave: 'home.porte.porta2.testo', sezione: 'Da dove entri · porta 2', etichetta: 'Testo', testo: 'Un documento con QR che attesta il tuo semaforo in un periodo, da mostrare a chi ti affitta casa.' },
        { chiave: 'home.porte.porta2.prodotto', sezione: 'Da dove entri · porta 2', etichetta: 'Nome del prodotto', testo: 'Certificato' },
        { chiave: 'home.porte.porta2.prezzo', sezione: 'Da dove entri · porta 2', etichetta: 'Prezzo (lo stesso testo è anche nella scheda del certificato, più giù)', testo: 'Gratuito con contratto CRIA attivo · {prezzo} su autocandidatura' },
        { chiave: 'home.porte.porta2.nota', sezione: 'Da dove entri · porta 2', etichetta: 'Nota in verde', testo: 'Sapere quali dati CRIA ha su di te è sempre gratuito: è un tuo diritto (art. 15 GDPR).' },
        { chiave: 'home.porte.porta2.pulsante', sezione: 'Da dove entri · porta 2', etichetta: 'Link in fondo', testo: 'Il tuo certificato' },
        { chiave: 'home.porte.porta3.chi', sezione: 'Da dove entri · porta 3', etichetta: 'Per chi', testo: 'Proprietario che vuole coprirsi' },
        { chiave: 'home.porte.porta3.domanda', sezione: 'Da dove entri · porta 3', etichetta: 'Domanda', testo: "«E se l'inquilino non paga?»" },
        { chiave: 'home.porte.porta3.testo', sezione: 'Da dove entri · porta 3', etichetta: 'Testo (sotto, i nomi dei prodotti vengono dal listino)', testo: 'Dalla sola segnalazione alla garanzia con incasso gestito da CRIA. Il prodotto si sceglie per ogni contratto.' },
        { chiave: 'home.porte.porta3.prezzo', sezione: 'Da dove entri · porta 3', etichetta: 'Prezzo', testo: 'Dal listino, sul canone che dichiari' },
        { chiave: 'home.porte.porta3.pulsante', sezione: 'Da dove entri · porta 3', etichetta: 'Link in fondo', testo: 'Scopri i prodotti' },
        { chiave: 'home.porte.porta4.chi', sezione: 'Da dove entri · porta 4', etichetta: 'Per chi (testo e prezzo vengono dal listino)', testo: 'Agenzia immobiliare' },
        { chiave: 'home.porte.porta4.domanda', sezione: 'Da dove entri · porta 4', etichetta: 'Domanda', testo: '«Posso verificare i candidati dei miei annunci?»' },
        { chiave: 'home.porte.porta4.pulsante', sezione: 'Da dove entri · porta 4', etichetta: 'Link in fondo', testo: 'Contattaci' },

        // ─── Il listino ───
        { chiave: 'home.listino.occhiello', sezione: 'Il listino', etichetta: 'Occhiello', testo: 'Per proprietari · Il listino' },
        { chiave: 'home.listino.titolo', sezione: 'Il listino', etichetta: 'Titolo', testo: 'Il prezzo lo fa il listino. *Nessun preventivo da aspettare.*' },
        { chiave: 'home.listino.sottotitolo', sezione: 'Il listino', etichetta: 'Sottotitolo', testo: 'Il prodotto sta sul contratto: con più immobili puoi sceglierne uno diverso per ciascuno. Il costo si calcola dal listino e dal canone che dichiari.', lungo: true },
        { chiave: 'home.listino.garanzia', sezione: 'Il listino · schede dei prodotti', etichetta: 'Riga della garanzia, se c’è ({mesi} è la franchigia, con la parola «mese» o «mesi»)', testo: 'Garanzia, franchigia {mesi}' },
        { chiave: 'home.listino.senzaGaranzia', sezione: 'Il listino · schede dei prodotti', etichetta: 'Riga della garanzia, se non c’è', testo: 'Nessuna garanzia' },
        { chiave: 'home.listino.incassaCria', sezione: 'Il listino · schede dei prodotti', etichetta: 'Riga dell’incasso, se incassa CRIA', testo: 'Incassa CRIA e ti bonifica il canone' },
        { chiave: 'home.listino.incassiTu', sezione: 'Il listino · schede dei prodotti', etichetta: 'Riga dell’incasso, se incassa il proprietario', testo: 'Incassi tu il canone' },
        { chiave: 'home.listino.pulsante', sezione: 'Il listino', etichetta: 'Pulsante', testo: 'Scopri i prodotti per proprietari' },
        { chiave: 'home.listino.nota', sezione: 'Il listino', etichetta: 'Frase accanto al pulsante', testo: "Con la garanzia, se l'inquilino non paga CRIA indennizza il proprietario. Con {nomeProdotto} segnali e costruisci lo storico, senza copertura.", lungo: true },

        // ─── Prima di firmare ───
        { chiave: 'home.prima.occhiello', sezione: 'Prima di firmare', etichetta: 'Occhiello', testo: 'Prima di firmare' },
        { chiave: 'home.prima.titolo', sezione: 'Prima di firmare', etichetta: 'Titolo', testo: 'Chi affitta verifica. *Chi cerca casa si certifica.*' },
        { chiave: 'home.prima.verifica.occhiello', sezione: 'Prima di firmare · scheda della verifica', etichetta: 'Occhiello (sotto, nome e prezzo vengono dal listino)', testo: 'Per chi sta per affittare' },
        { chiave: 'home.prima.verifica.punto1', sezione: 'Prima di firmare · scheda della verifica', etichetta: 'Punto 1', testo: 'Serve un account con i dati di fatturazione completi.' },
        { chiave: 'home.prima.verifica.punto2', sezione: 'Prima di firmare · scheda della verifica', etichetta: 'Punto 2', testo: 'Inserisci nome, cognome, data e luogo di nascita e codice fiscale del candidato.' },
        { chiave: 'home.prima.verifica.punto3', sezione: 'Prima di firmare · scheda della verifica', etichetta: 'Punto 3', testo: "Entro {ore} ore ti arriva un'email che ti invita ad accedere: l'esito si legge solo dentro la piattaforma." },
        { chiave: 'home.prima.verifica.punto4', sezione: 'Prima di firmare · scheda della verifica', etichetta: 'Punto 4', testo: "L'esito è il semaforo con una breve sintesi, oppure «non abbiamo informazioni in merito». Il resto lo vede solo chi ha il contratto.", lungo: true },
        { chiave: 'home.prima.verifica.punto5', sezione: 'Prima di firmare · scheda della verifica', etichetta: 'Punto 5 ({giorni} contiene anche la parola «giorni»)', testo: "I {prezzo} si scalano dal primo prodotto che acquisti entro {giorni}, sullo stesso account: un'interrogazione per acquisto.", lungo: true },
        { chiave: 'home.prima.verifica.esempio.finestra', sezione: 'Prima di firmare · esito d’esempio', etichetta: 'Barra della finestra', testo: 'Esito {nomeProdotto}' },
        { chiave: 'home.prima.verifica.esempio.candidato', sezione: 'Prima di firmare · esito d’esempio', etichetta: 'Titoletto', testo: 'Candidato' },
        { chiave: 'home.prima.verifica.esempio.nome', sezione: 'Prima di firmare · esito d’esempio', etichetta: 'Nome del candidato d’esempio', testo: 'Giulia R.' },
        { chiave: 'home.prima.verifica.esempio.sintesi', sezione: 'Prima di firmare · esito d’esempio', etichetta: 'Titoletto della sintesi', testo: 'Sintesi' },
        { chiave: 'home.prima.verifica.esempio.sintesiTesto', sezione: 'Prima di firmare · esito d’esempio', etichetta: 'Sintesi', testo: 'Pagamenti rilevati da CRIA negli ultimi {mesi} mesi su due contratti, nessun mese non pagato.' },
        { chiave: 'home.prima.verifica.esempio.oppure', sezione: 'Prima di firmare · esito d’esempio', etichetta: 'Riga in fondo', testo: 'Oppure: «non abbiamo informazioni in merito».' },
        { chiave: 'home.prima.verifica.pulsante', sezione: 'Prima di firmare · scheda della verifica', etichetta: 'Pulsante', testo: 'Verifica un candidato' },

        { chiave: 'home.prima.certificato.occhiello', sezione: 'Prima di firmare · scheda del certificato', etichetta: 'Occhiello', testo: 'Per inquilini' },
        { chiave: 'home.prima.certificato.titolo', sezione: 'Prima di firmare · scheda del certificato', etichetta: 'Titolo', testo: 'Il certificato' },
        { chiave: 'home.prima.certificato.prezzo', sezione: 'Prima di firmare · scheda del certificato', etichetta: 'Prezzo (lo stesso testo è anche nella porta 2, più su)', testo: 'Gratuito con contratto CRIA attivo · {prezzo} su autocandidatura' },
        { chiave: 'home.prima.certificato.punto1', sezione: 'Prima di firmare · scheda del certificato', etichetta: 'Punto 1', testo: 'Attesta un periodo, non un istante: «dal … al …, semaforo …».' },
        { chiave: 'home.prima.certificato.punto2', sezione: 'Prima di firmare · scheda del certificato', etichetta: 'Punto 2 ({mesi} contiene anche la parola «mesi»)', testo: "Vale {mesi} dall'emissione, poi si rigenera con i dati aggiornati." },
        { chiave: 'home.prima.certificato.punto3', sezione: 'Prima di firmare · scheda del certificato', etichetta: 'Punto 3', testo: 'Ha QR e codice univoco, codice fiscale mascherato, e dichiara da dove viene il dato.' },
        { chiave: 'home.prima.certificato.punto4', sezione: 'Prima di firmare · scheda del certificato', etichetta: 'Punto 4', testo: "Chi lo riceve lo verifica gratis su una pagina pubblica, senza registrarsi, e vede anche se il semaforo è peggiorato dopo l'emissione.", lungo: true },
        { chiave: 'home.prima.certificato.punto5', sezione: 'Prima di firmare · scheda del certificato', etichetta: 'Punto 5', testo: 'Consegnare il codice è il tuo consenso. Puoi revocarlo, e vedi quante volte è stato verificato.' },
        { chiave: 'home.prima.certificato.punto6', sezione: 'Prima di firmare · scheda del certificato', etichetta: 'Punto 6', testo: "Senza storico CRIA? Con l'autocandidatura ({prezzo}) porti tu la documentazione e CRIA la istruisce." },
        { chiave: 'home.prima.certificato.esempio.finestra', sezione: 'Prima di firmare · certificato d’esempio', etichetta: 'Barra della finestra', testo: 'Certificato CRIA' },
        { chiave: 'home.prima.certificato.esempio.periodo', sezione: 'Prima di firmare · certificato d’esempio', etichetta: 'Titoletto del periodo', testo: 'Periodo certificato' },
        { chiave: 'home.prima.certificato.esempio.date', sezione: 'Prima di firmare · certificato d’esempio', etichetta: 'Periodo', testo: 'dal {dal} al {al}' },
        { chiave: 'home.prima.certificato.esempio.semaforo', sezione: 'Prima di firmare · certificato d’esempio', etichetta: 'Etichetta del semaforo ({semaforo} viene dal semaforo)', testo: 'Semaforo {semaforo}' },
        { chiave: 'home.prima.certificato.esempio.fonte', sezione: 'Prima di firmare · certificato d’esempio', etichetta: 'Riga 1 · voce', testo: 'Fonte del dato' },
        { chiave: 'home.prima.certificato.esempio.fonteValore', sezione: 'Prima di firmare · certificato d’esempio', etichetta: 'Riga 1 · valore', testo: 'Rilevato da CRIA' },
        { chiave: 'home.prima.certificato.esempio.codiceFiscale', sezione: 'Prima di firmare · certificato d’esempio', etichetta: 'Riga 2 · voce', testo: 'Codice fiscale' },
        { chiave: 'home.prima.certificato.esempio.emesso', sezione: 'Prima di firmare · certificato d’esempio', etichetta: 'Riga 3 · voce', testo: 'Emesso il' },
        { chiave: 'home.prima.certificato.esempio.valido', sezione: 'Prima di firmare · certificato d’esempio', etichetta: 'Riga 4 · voce', testo: 'Valido fino al' },
        { chiave: 'home.prima.certificato.esempio.codice', sezione: 'Prima di firmare · certificato d’esempio', etichetta: 'Riga 5 · voce', testo: 'Codice' },
        { chiave: 'home.prima.certificato.esempio.codiceValore', sezione: 'Prima di firmare · certificato d’esempio', etichetta: 'Riga 5 · codice d’esempio', testo: 'K7Q2-94HF-3XDM' },
        { chiave: 'home.prima.certificato.nota', sezione: 'Prima di firmare · scheda del certificato', etichetta: 'Nota in verde (la prima frase è anche nella porta 2, più su)', testo: 'Sapere quali dati CRIA ha su di te è sempre gratuito: è un tuo diritto (art. 15 GDPR). Il certificato è il documento da mostrare a terzi, non la strada per vedere i tuoi dati.', lungo: true },
        { chiave: 'home.prima.certificato.pulsante', sezione: 'Prima di firmare · scheda del certificato', etichetta: 'Pulsante', testo: 'Il tuo certificato' },

        // ─── Il mese, in breve ───
        { chiave: 'home.mese.occhiello', sezione: 'Il mese, in breve', etichetta: 'Occhiello', testo: 'Il mese, in breve' },
        { chiave: 'home.mese.titolo', sezione: 'Il mese, in breve', etichetta: 'Titolo', testo: 'Ogni mese, una domanda: *il canone è arrivato?*' },
        { chiave: 'home.mese.sottotitolo', sezione: 'Il mese, in breve', etichetta: 'Sottotitolo ({prodotti} sono i prodotti in cui il proprietario incassa da sé)', testo: 'Vale per chi incassa da sé il canone, con {prodotti}.' },
        { chiave: 'home.mese.passo1.quando', sezione: 'Il mese, in breve · passi', etichetta: 'Passo 1 · quando', testo: 'Giorno {giorno}' },
        { chiave: 'home.mese.passo1.titolo', sezione: 'Il mese, in breve · passi', etichetta: 'Passo 1 · titolo', testo: 'Scade il canone' },
        { chiave: 'home.mese.passo1.testo', sezione: 'Il mese, in breve · passi', etichetta: 'Passo 1 · testo', testo: 'Da qui parte il conto dei giorni.' },
        { chiave: 'home.mese.passo2.quando', sezione: 'Il mese, in breve · passi', etichetta: 'Passo 2 · quando ({numero} è quanti promemoria partono)', testo: '{numero} promemoria' },
        { chiave: 'home.mese.passo2.titolo', sezione: 'Il mese, in breve · passi', etichetta: 'Passo 2 · titolo', testo: '«Il canone è arrivato?»' },
        { chiave: 'home.mese.passo2.testo', sezione: 'Il mese, in breve · passi', etichetta: 'Passo 2 · testo ({solleciti} sono i momenti dei promemoria, dalle regole)', testo: '{solleciti}, per notifica, email e SMS. Si risponde sì o no.' },
        { chiave: 'home.mese.passo3.quando', sezione: 'Il mese, in breve · passi', etichetta: 'Passo 3 · quando ({giorni} contiene anche la parola «giorni»)', testo: 'Entro {giorni}' },
        { chiave: 'home.mese.passo3.titolo', sezione: 'Il mese, in breve · passi', etichetta: 'Passo 3 · titolo', testo: 'Segnali il mancato pagamento' },
        { chiave: 'home.mese.passo3.testo', sezione: 'Il mese, in breve · passi', etichetta: 'Passo 3 · testo ({giorni} contiene anche la parola «giorni»)', testo: 'Nei {giorni} dalla scadenza: copertura attiva, e la pratica di morosità parte subito.' },
        { chiave: 'home.mese.passo4.quando', sezione: 'Il mese, in breve · passi', etichetta: 'Passo 4 · quando ({giorni} contiene anche la parola «giorni»)', testo: 'Dopo {giorni}' },
        { chiave: 'home.mese.passo4.titolo', sezione: 'Il mese, in breve · passi', etichetta: 'Passo 4 · titolo', testo: 'Segnali in ritardo' },
        { chiave: 'home.mese.passo4.testo', sezione: 'Il mese, in breve · passi', etichetta: 'Passo 4 · testo', testo: "Per l'inquilino il mese conta comunque come non pagato, perché è la verità. La copertura di quel mese decade." },
        { chiave: 'home.mese.passo5.quando', sezione: 'Il mese, in breve · passi', etichetta: 'Passo 5 · quando', testo: 'Giorno {giorno}' },
        { chiave: 'home.mese.passo5.titolo', sezione: 'Il mese, in breve · passi', etichetta: 'Passo 5 · titolo', testo: 'Nessuna segnalazione' },
        { chiave: 'home.mese.passo5.testo', sezione: 'Il mese, in breve · passi', etichetta: 'Passo 5 · testo', testo: 'Il mese diventa non rilevato: non conta nel semaforo e non è coperto. La copertura riprende dal primo mese segnalato correttamente.', lungo: true },
        { chiave: 'home.mese.poi', sezione: 'Il mese, in breve · E poi', etichetta: 'Titoletto del riquadro', testo: 'E poi' },
        { chiave: 'home.mese.nota1.titolo', sezione: 'Il mese, in breve · E poi', etichetta: 'Scheda 1 · titolo', testo: 'Non coperto non vuol dire non gestito' },
        { chiave: 'home.mese.nota1.testo', sezione: 'Il mese, in breve · E poi', etichetta: 'Scheda 1 · testo', testo: "La pratica di morosità si apre comunque e il recupero parte: piano di rientro con l'inquilino, avvocato se serve. Sui mesi coperti dalla garanzia, CRIA indennizza il proprietario.", lungo: true },
        { chiave: 'home.mese.nota2.titolo', sezione: 'Il mese, in breve · E poi', etichetta: 'Scheda 2 · titolo', testo: '{nomeProdotto}: niente da segnalare' },
        { chiave: 'home.mese.nota2.testo', sezione: 'Il mese, in breve · E poi', etichetta: 'Scheda 2 · testo', testo: 'Incassa CRIA, quindi sa già se il canone è arrivato.' },
        { chiave: 'home.mese.nota3.titolo', sezione: 'Il mese, in breve · E poi', etichetta: 'Scheda 3 · titolo', testo: '{nomeProdotto}: nessuna copertura' },
        { chiave: 'home.mese.nota3.testo', sezione: 'Il mese, in breve · E poi', etichetta: 'Scheda 3 · testo', testo: "Le segnalazioni contano per il semaforo dell'inquilino, senza garanzia." },
        { chiave: 'home.mese.nota4.titolo', sezione: 'Il mese, in breve · E poi', etichetta: 'Scheda 4 · titolo', testo: 'La contestazione' },
        { chiave: 'home.mese.nota4.testo', sezione: 'Il mese, in breve · E poi', etichetta: 'Scheda 4 · testo ({giorniContestazione} e {giorniRisposta} contengono anche la parola «giorni»)', testo: "Solo l'inquilino, solo su un «non pagato», entro {giorniContestazione} dalla segnalazione e con una prova, come la ricevuta del bonifico. CRIA decide sulle prove delle due parti e risponde entro {giorniRisposta}. Finché è aperta, il mese non conta.", lungo: true },
        { chiave: 'home.mese.pulsante', sezione: 'Il mese, in breve', etichetta: 'Pulsante', testo: 'Vedi il ciclo nel dettaglio' },

        // ─── Chiusura ───
        { chiave: 'home.chiusura.occhiello', sezione: 'Chiusura', etichetta: 'Occhiello', testo: 'Per iniziare' },
        { chiave: 'home.chiusura.titolo', sezione: 'Chiusura', etichetta: 'Titolo', testo: 'Un account solo, *anche con due ruoli.*' },
        { chiave: 'home.chiusura.testo', sezione: 'Chiusura', etichetta: 'Testo', testo: "Ti registri come persona fisica o come società. Una persona del nostro team verifica la tua identità dal documento che carichi, anche se entri con Google. Con lo stesso account puoi essere proprietario e inquilino, e passi da un ruolo all'altro dal selettore del contesto.", lungo: true },
        { chiave: 'home.chiusura.punto1', sezione: 'Chiusura', etichetta: 'Punto 1 · documenti', testo: 'Ognuno carica i propri documenti. Il candidato inquilino lo fa da un link personale, con informativa e consenso: il proprietario vede quali mancano, non i documenti.', lungo: true },
        { chiave: 'home.chiusura.punto2', sezione: 'Chiusura', etichetta: 'Punto 2 · movimenti bancari', testo: "Dei movimenti bancari servono solo i pagamenti del canone degli ultimi {mesi} mesi, non l'estratto conto intero." },
        { chiave: 'home.chiusura.punto3', sezione: 'Chiusura', etichetta: 'Punto 3 · contratto', testo: 'Il contratto si firma elettronicamente in piattaforma. CRIA non lo registra: ne riceve i dati di registrazione.' },
        { chiave: 'home.chiusura.pulsanteInizia', sezione: 'Chiusura', etichetta: 'Pulsante bianco', testo: 'Inizia' },
        { chiave: 'home.chiusura.pulsanteRegistrati', sezione: 'Chiusura', etichetta: 'Pulsante con il bordo', testo: 'Registrati' },
        { chiave: 'home.chiusura.giaRegistrato', sezione: 'Chiusura', etichetta: 'Frase prima del link per accedere', testo: 'Hai già un account?' },
        { chiave: 'home.chiusura.accedi', sezione: 'Chiusura', etichetta: 'Link per accedere', testo: 'Accedi' },
        { chiave: 'home.chiusura.domande', sezione: 'Chiusura', etichetta: 'Frase prima del link al supporto', testo: 'Domande?' },
        { chiave: 'home.chiusura.supporto', sezione: 'Chiusura', etichetta: 'Link al supporto', testo: 'Supporto' },
    ],
};
