// Testi della pagina Per inquilini (/per-inquilini) — l'admin li cambia da Admin → Testi.
// Nomi dei prodotti, prezzi, giorni, mesi, le etichette del semaforo e degli esiti
// del mese non si scrivono qui: arrivano dal listino (data/catalogo.js) e dal
// semaforo (lib/semaforo.js) attraverso i segnaposto {…}.
// Le domande frequenti di questa pagina non stanno qui: le scrive l'admin da FAQ.
export default {
    id: 'perInquilini',
    nome: 'Per inquilini',
    percorso: '/per-inquilini',
    ordine: 30,
    testi: [
        { chiave: 'perInquilini.meta.titolo', sezione: 'Motori di ricerca', etichetta: 'Titolo della scheda del browser', testo: 'Per inquilini — CRIA' },
        { chiave: 'perInquilini.meta.descrizione', sezione: 'Motori di ricerca', etichetta: 'Descrizione per i motori di ricerca', testo: 'Il tuo semaforo lo vedi sempre, con la spiegazione di come si costruisce. Contestazione con prova, certificato gratuito con un contratto CRIA attivo, autocandidatura per chi non ha storico.', lungo: true },

        { chiave: 'perInquilini.hero.occhiello', sezione: 'In alto', etichetta: 'Etichetta sopra il titolo', testo: 'Per inquilini' },
        { chiave: 'perInquilini.hero.titolo', sezione: 'In alto', etichetta: 'Titolo', testo: 'Il tuo semaforo\n*lo vedi sempre.*' },
        { chiave: 'perInquilini.hero.sottotitolo', sezione: 'In alto', etichetta: 'Sottotitolo', testo: "CRIA registra come paghi l'affitto e ne ricava il tuo semaforo. Tu lo vedi in ogni momento, insieme alla spiegazione di come si costruisce. E se hai un contratto CRIA attivo, il certificato da mostrare al prossimo proprietario è gratuito.", lungo: true },
        { chiave: 'perInquilini.hero.pulsanteSemaforo', sezione: 'In alto', etichetta: 'Pulsante principale (porta a come si costruisce)', testo: 'Come si costruisce' },
        { chiave: 'perInquilini.hero.pulsanteCertificato', sezione: 'In alto', etichetta: 'Pulsante secondario (porta al certificato)', testo: 'Il certificato' },

        { chiave: 'perInquilini.schedaSemaforo.titolo', sezione: 'In alto · il semaforo d’esempio', etichetta: 'Scritta in cima al riquadro', testo: 'Il tuo semaforo' },
        { chiave: 'perInquilini.esempi.nome', sezione: 'In alto · il semaforo d’esempio', etichetta: 'Nome della persona d’esempio (anche nel certificato d’esempio)', testo: 'Giulia Rossi' },
        { chiave: 'perInquilini.esempi.etichetta', sezione: 'In alto · il semaforo d’esempio', etichetta: 'Etichetta «Esempio» (su tutti i riquadri d’esempio della pagina)', testo: 'Esempio' },
        { chiave: 'perInquilini.schedaSemaforo.media', sezione: 'In alto · il semaforo d’esempio', etichetta: 'Riga sotto il colore', testo: 'Giorno medio di pagamento: {media} · ultimi {mesi} mesi' },
        { chiave: 'perInquilini.schedaSemaforo.meseAMese', sezione: 'In alto · il semaforo d’esempio', etichetta: 'Titolo della striscia dei mesi', testo: 'Mese per mese' },
        { chiave: 'perInquilini.schedaSemaforo.nota', sezione: 'In alto · il semaforo d’esempio', etichetta: 'Nota in fondo al riquadro', testo: 'Calcolato su di te, su tutti i tuoi contratti. Mesi non rilevati: {mesiNonRilevati}, pesano zero.' },
        { chiave: 'perInquilini.schedaSemaforo.ultimoCanone', sezione: 'In alto · il semaforo d’esempio', etichetta: 'Riquadro blu · occhiello', testo: 'Canone di {mese}' },
        { chiave: 'perInquilini.schedaSemaforo.ultimoEsito', sezione: 'In alto · il semaforo d’esempio', etichetta: 'Riquadro blu · testo', testo: 'Pagato · {esito}' },

        { chiave: 'perInquilini.costruzione.occhiello', sezione: 'Come si costruisce', etichetta: 'Occhiello', testo: 'Come si costruisce' },
        { chiave: 'perInquilini.costruzione.titolo', sezione: 'Come si costruisce', etichetta: 'Titolo', testo: 'Conta una cosa sola: *il giorno in cui paghi.*' },
        { chiave: 'perInquilini.costruzione.intro', sezione: 'Come si costruisce', etichetta: 'Testo sotto il titolo', testo: "Il semaforo è la media del giorno del mese in cui hai pagato il canone negli ultimi {mesi} mesi. Si calcola su di te, su tutti i tuoi contratti d'affitto, non su un contratto solo.", lungo: true },
        { chiave: 'perInquilini.costruzione.regola1.titolo', sezione: 'Come si costruisce', etichetta: 'Regola 1 · titolo', testo: 'Mese {nonRilevato}' },
        { chiave: 'perInquilini.costruzione.regola1.testo', sezione: 'Come si costruisce', etichetta: 'Regola 1 · testo', testo: 'Se nessuno ha segnalato quel mese, pesa zero: non conta né a favore né contro di te.' },
        { chiave: 'perInquilini.costruzione.regola2.titolo', sezione: 'Come si costruisce', etichetta: 'Regola 2 · titolo', testo: 'Mese contestato' },
        { chiave: 'perInquilini.costruzione.regola2.testo', sezione: 'Come si costruisce', etichetta: 'Regola 2 · testo', testo: 'Finché la contestazione è aperta, quel mese resta fuori dal calcolo.' },
        { chiave: 'perInquilini.costruzione.regola3.titolo', sezione: 'Come si costruisce', etichetta: 'Regola 3 · titolo', testo: 'Nessuno lo cambia a mano' },
        { chiave: 'perInquilini.costruzione.regola3.testo', sezione: 'Come si costruisce', etichetta: 'Regola 3 · testo', testo: 'Nessuno in CRIA può modificare un semaforo. Lo corregge solo una contestazione istruita.' },

        { chiave: 'perInquilini.mese.occhiello', sezione: 'Ogni mese', etichetta: 'Occhiello', testo: 'Ogni mese' },
        { chiave: 'perInquilini.mese.titolo', sezione: 'Ogni mese', etichetta: 'Titolo', testo: 'Pagare {fasciaPuntuale} *è quello che conta.*' },
        { chiave: 'perInquilini.mese.esempio.intestazione', sezione: 'Ogni mese', etichetta: 'Calendario d’esempio · occhiello', testo: 'Il mese del canone' },
        { chiave: 'perInquilini.mese.esempio.titolo', sezione: 'Ogni mese', etichetta: 'Calendario d’esempio · titolo', testo: 'Il giorno in cui paghi' },
        { chiave: 'perInquilini.mese.esempio.giorno', sezione: 'Ogni mese', etichetta: 'Calendario d’esempio · etichetta del giorno', testo: 'giorno {giorno}' },
        { chiave: 'perInquilini.mese.esempio.scadenza', sezione: 'Ogni mese', etichetta: 'Calendario d’esempio · il giorno della scadenza', testo: 'scade il canone' },
        { chiave: 'perInquilini.mese.esempio.chiusura', sezione: 'Ogni mese', etichetta: 'Calendario d’esempio · il giorno di chiusura', testo: 'se nessuno ha segnalato, il mese diventa {nonRilevato}' },
        { chiave: 'perInquilini.mese.passo1.titolo', sezione: 'Ogni mese', etichetta: 'Passo 1 · titolo', testo: 'Il giorno {giorno} scade il canone' },
        { chiave: 'perInquilini.mese.passo1.testo', sezione: 'Ogni mese', etichetta: 'Passo 1 · testo', testo: 'Se in media paghi {fasciaPuntuale}, il tuo semaforo è {semaforoVerde}. In media {fasciaRitardo} diventa {semaforoGiallo}; {fasciaGrave}, o con un mese non pagato, {semaforoRosso}.', lungo: true },
        { chiave: 'perInquilini.mese.passo2.titolo', sezione: 'Ogni mese', etichetta: 'Passo 2 · titolo', testo: 'Il proprietario risponde a una domanda' },
        { chiave: 'perInquilini.mese.passo2.testo', sezione: 'Ogni mese', etichetta: 'Passo 2 · testo', testo: 'Riceve promemoria per notifica, email e SMS con una sola domanda: «il canone è arrivato? sì / no». La sua risposta la vedi anche tu.', lungo: true },
        { chiave: 'perInquilini.mese.passo3.titolo', sezione: 'Ogni mese', etichetta: 'Passo 3 · titolo', testo: 'Se il canone non è arrivato' },
        { chiave: 'perInquilini.mese.passo3.testo', sezione: 'Ogni mese', etichetta: 'Passo 3 · testo', testo: 'Si apre una pratica di morosità: si cerca con te un piano di rientro, e se serve interviene un avvocato. Se il proprietario segnala il mancato pagamento in ritardo, il mese conta comunque come non pagato, perché è quello che è successo.', lungo: true },
        { chiave: 'perInquilini.mese.passo4.titolo', sezione: 'Ogni mese', etichetta: 'Passo 4 · titolo', testo: 'Se al giorno {giorno} nessuno ha segnalato' },
        { chiave: 'perInquilini.mese.passo4.testo', sezione: 'Ogni mese', etichetta: 'Passo 4 · testo', testo: 'Il mese diventa {nonRilevato}: nel tuo semaforo pesa zero, né a favore né contro.' },
        { chiave: 'perInquilini.mese.notaIncassaCria', sezione: 'Ogni mese', etichetta: 'Riquadro in fondo', testo: '**Con {nomeProdotto}** il canone lo paghi a CRIA, che lo gira al proprietario: il mese si registra senza che nessuno debba segnalare nulla.', lungo: true },

        { chiave: 'perInquilini.contestazione.occhiello', sezione: 'La contestazione', etichetta: 'Occhiello', testo: 'Se una segnalazione è sbagliata' },
        { chiave: 'perInquilini.contestazione.titolo', sezione: 'La contestazione', etichetta: 'Titolo', testo: 'Contesti con la prova. *Decidono le evidenze.*' },
        { chiave: 'perInquilini.contestazione.intro', sezione: 'La contestazione', etichetta: 'Testo sotto il titolo', testo: 'Se il proprietario segnala come non pagato un canone che hai pagato, puoi contestare allegando la prova, per esempio la ricevuta del bonifico.', lungo: true },
        { chiave: 'perInquilini.contestazione.punto1', sezione: 'La contestazione', etichetta: 'Punto 1', testo: 'Solo tu puoi contestare, e solo una segnalazione di mancato pagamento' },
        { chiave: 'perInquilini.contestazione.punto2', sezione: 'La contestazione', etichetta: 'Punto 2', testo: 'Hai {giorni} giorni dalla segnalazione, con la prova allegata' },
        { chiave: 'perInquilini.contestazione.punto3', sezione: 'La contestazione', etichetta: 'Punto 3', testo: 'CRIA decide sulle evidenze tue e del proprietario' },
        { chiave: 'perInquilini.contestazione.punto4', sezione: 'La contestazione', etichetta: 'Punto 4', testo: 'Risponde entro {giorni} giorni; intanto quel mese non conta' },
        { chiave: 'perInquilini.contestazione.esempio.intestazione', sezione: 'La contestazione', etichetta: 'Segnalazione d’esempio · occhiello', testo: 'Segnalazione del proprietario' },
        { chiave: 'perInquilini.contestazione.esempio.segnalatoIl', sezione: 'La contestazione', etichetta: 'Segnalazione d’esempio · voce della data', testo: 'Segnalato il' },
        { chiave: 'perInquilini.contestazione.esempio.contestabileEntro', sezione: 'La contestazione', etichetta: 'Segnalazione d’esempio · voce della scadenza', testo: 'Contestabile entro' },
        { chiave: 'perInquilini.contestazione.esempio.allegato', sezione: 'La contestazione', etichetta: 'Segnalazione d’esempio · nome del file allegato', testo: 'ricevuta-bonifico.pdf' },
        { chiave: 'perInquilini.contestazione.esempio.allegatoNota', sezione: 'La contestazione', etichetta: 'Segnalazione d’esempio · sotto il file', testo: 'La prova che hai pagato' },
        { chiave: 'perInquilini.contestazione.esempio.pulsante', sezione: 'La contestazione', etichetta: 'Segnalazione d’esempio · pulsante', testo: 'Contesta' },
        { chiave: 'perInquilini.contestazione.esempio.nota', sezione: 'La contestazione', etichetta: 'Segnalazione d’esempio · riquadro in fondo', testo: 'Il mese è fuori dal calcolo del semaforo. CRIA decide sulle prove di entrambi e risponde entro {giorni} giorni.' },

        { chiave: 'perInquilini.certificato.occhiello', sezione: 'Il certificato', etichetta: 'Occhiello', testo: 'Il certificato' },
        { chiave: 'perInquilini.certificato.titolo', sezione: 'Il certificato', etichetta: 'Titolo', testo: 'Certifica un periodo, *non un istante.*' },
        { chiave: 'perInquilini.certificato.intro', sezione: 'Il certificato', etichetta: 'Testo sotto il titolo', testo: 'Il certificato dice come hai pagato in un periodo preciso, dal … al …, con il semaforo di quel periodo. Ha un QR e un codice univoco, il codice fiscale mascherato e la fonte del dato: «{fonteCria}» oppure «{fonteDocumenti}».', lungo: true },
        { chiave: 'perInquilini.certificato.fonteCria', sezione: 'Il certificato', etichetta: 'Fonte del dato «da CRIA» (anche nel certificato d’esempio)', testo: 'Rilevato da CRIA' },
        { chiave: 'perInquilini.certificato.fonteDocumenti', sezione: 'Il certificato', etichetta: 'Fonte del dato «da documenti» (anche nell’autocandidatura)', testo: 'Verificato su documentazione fornita dall’interessato' },
        { chiave: 'perInquilini.certificato.prezzo.occhiello', sezione: 'Il certificato', etichetta: 'Riquadro del prezzo · occhiello', testo: 'Certificato' },
        { chiave: 'perInquilini.certificato.prezzo.titolo', sezione: 'Il certificato', etichetta: 'Riquadro del prezzo · in grande', testo: 'Gratuito' },
        { chiave: 'perInquilini.certificato.prezzo.condizione', sezione: 'Il certificato', etichetta: 'Riquadro del prezzo · condizione', testo: 'se hai un contratto CRIA attivo.' },
        { chiave: 'perInquilini.certificato.prezzo.autocandidatura', sezione: 'Il certificato', etichetta: 'Riquadro del prezzo · pulsante per l’autocandidatura', testo: "Senza storico su CRIA: {prezzo} con l'autocandidatura" },
        { chiave: 'perInquilini.certificato.dati.occhiello', sezione: 'Il certificato', etichetta: 'Riquadro dei tuoi dati · occhiello', testo: 'I tuoi dati · sempre gratis' },
        { chiave: 'perInquilini.certificato.dati.testo', sezione: 'Il certificato', etichetta: 'Riquadro dei tuoi dati · testo', testo: "Sapere cosa CRIA conserva su di te è un tuo diritto (art. 15 GDPR) e non si paga. Il certificato è un'altra cosa: un documento fatto per essere mostrato a un terzo.", lungo: true },
        { chiave: 'perInquilini.certificato.dati.link', sezione: 'Il certificato', etichetta: 'Riquadro dei tuoi dati · link', testo: 'Chiedi i tuoi dati' },
        { chiave: 'perInquilini.certificato.esempio.intestazione', sezione: 'Il certificato', etichetta: 'Certificato d’esempio · scritta in cima', testo: 'Certificato CRIA' },
        { chiave: 'perInquilini.certificato.esempio.marchio', sezione: 'Il certificato', etichetta: 'Certificato d’esempio · sotto il nome CRIA', testo: 'Centrale Rischi Immobiliare Affitti' },
        { chiave: 'perInquilini.certificato.esempio.tipo', sezione: 'Il certificato', etichetta: 'Certificato d’esempio · tipo di documento', testo: 'Certificato' },
        { chiave: 'perInquilini.certificato.esempio.intestatario', sezione: 'Il certificato', etichetta: 'Certificato d’esempio · voce dell’intestatario', testo: 'Intestatario' },
        { chiave: 'perInquilini.certificato.esempio.codiceFiscale', sezione: 'Il certificato', etichetta: 'Certificato d’esempio · voce del codice fiscale', testo: 'Codice fiscale' },
        { chiave: 'perInquilini.certificato.esempio.codiceFiscaleValore', sezione: 'Il certificato', etichetta: 'Certificato d’esempio · codice fiscale mascherato', testo: 'RSS••••••••••••X' },
        { chiave: 'perInquilini.certificato.esempio.periodo', sezione: 'Il certificato', etichetta: 'Certificato d’esempio · voce del periodo', testo: 'Periodo certificato' },
        { chiave: 'perInquilini.certificato.esempio.periodoDate', sezione: 'Il certificato', etichetta: 'Certificato d’esempio · il periodo', testo: 'dal {dataInizio} al {dataFine}' },
        { chiave: 'perInquilini.certificato.esempio.semaforo', sezione: 'Il certificato', etichetta: 'Certificato d’esempio · il semaforo', testo: 'Semaforo {semaforo}' },
        { chiave: 'perInquilini.certificato.esempio.fonte', sezione: 'Il certificato', etichetta: 'Certificato d’esempio · voce della fonte', testo: 'Fonte del dato' },
        { chiave: 'perInquilini.certificato.esempio.emesso', sezione: 'Il certificato', etichetta: 'Certificato d’esempio · voce dell’emissione', testo: 'Emesso il' },
        { chiave: 'perInquilini.certificato.esempio.validoFino', sezione: 'Il certificato', etichetta: 'Certificato d’esempio · voce della validità', testo: 'Valido fino al' },
        { chiave: 'perInquilini.certificato.esempio.codice', sezione: 'Il certificato', etichetta: 'Certificato d’esempio · voce del codice', testo: 'Codice univoco' },
        { chiave: 'perInquilini.certificato.esempio.codiceValore', sezione: 'Il certificato', etichetta: 'Certificato d’esempio · il codice', testo: 'K7P2-9QXW-M4TR' },
        { chiave: 'perInquilini.certificato.esempio.avviso', sezione: 'Il certificato', etichetta: 'Certificato d’esempio · avviso in fondo', testo: 'Da solo questo foglio non fa fede: verificalo con il QR o con il codice.' },
        { chiave: 'perInquilini.certificato.dettaglio1.titolo', sezione: 'Il certificato', etichetta: 'Scheda 1 · titolo', testo: 'Chi lo riceve, lo verifica' },
        { chiave: 'perInquilini.certificato.dettaglio1.testo', sezione: 'Il certificato', etichetta: 'Scheda 1 · testo', testo: 'Gratis, su una pagina pubblica, senza registrarsi. Vede se è autentico, il periodo e il semaforo certificati, emissione e validità, e se dopo l’emissione il tuo semaforo è peggiorato, senza sapere di quanto.', lungo: true },
        { chiave: 'perInquilini.certificato.dettaglio2.titolo', sezione: 'Il certificato', etichetta: 'Scheda 2 · titolo', testo: 'Il controllo resta a te' },
        { chiave: 'perInquilini.certificato.dettaglio2.testo', sezione: 'Il certificato', etichetta: 'Scheda 2 · testo', testo: 'Consegnare il codice è il tuo consenso. Puoi revocarlo, e vedi quante volte il certificato è stato verificato, non da chi.', lungo: true },
        { chiave: 'perInquilini.certificato.dettaglio3.titolo', sezione: 'Il certificato', etichetta: 'Scheda 3 · titolo', testo: 'Vale {mesi} mesi' },
        { chiave: 'perInquilini.certificato.dettaglio3.testo', sezione: 'Il certificato', etichetta: 'Scheda 3 · testo', testo: 'Dalla data di emissione. Poi si rigenera con i dati aggiornati.' },

        { chiave: 'perInquilini.autocandidatura.occhiello', sezione: 'L’autocandidatura', etichetta: 'Occhiello', testo: '{nomeProdotto} · {prezzo}' },
        { chiave: 'perInquilini.autocandidatura.titolo', sezione: 'L’autocandidatura', etichetta: 'Titolo', testo: 'Nessuno storico su CRIA? *Lo porti tu.*' },
        { chiave: 'perInquilini.autocandidatura.intro', sezione: 'L’autocandidatura', etichetta: 'Testo sotto il titolo', testo: "Se non hai mai avuto un contratto su CRIA, il certificato lo chiedi con l'autocandidatura. Porti la tua documentazione e CRIA la istruisce: servono almeno due prove forti e indipendenti, su almeno {mesi} mesi. Queste sono le prove forti.", lungo: true },
        { chiave: 'perInquilini.autocandidatura.prova1.titolo', sezione: 'L’autocandidatura', etichetta: 'Prova 1 · titolo', testo: 'Movimenti bancari' },
        { chiave: 'perInquilini.autocandidatura.prova1.testo', sezione: 'L’autocandidatura', etichetta: 'Prova 1 · testo', testo: "Solo i movimenti dei pagamenti del canone degli ultimi {mesi} mesi, non l'estratto conto intero." },
        { chiave: 'perInquilini.autocandidatura.prova2.titolo', sezione: 'L’autocandidatura', etichetta: 'Prova 2 · titolo', testo: 'Referenza del precedente proprietario' },
        { chiave: 'perInquilini.autocandidatura.prova2.testo', sezione: 'L’autocandidatura', etichetta: 'Prova 2 · testo', testo: 'CRIA la conferma con un link personale inviato al recapito indicato sul contratto di locazione. Se dopo tre tentativi non risponde, il certificato riporta «referenza richiesta, non riscontrata».', lungo: true },
        { chiave: 'perInquilini.autocandidatura.prova3.titolo', sezione: 'L’autocandidatura', etichetta: 'Prova 3 · titolo', testo: 'Contratto registrato' },
        { chiave: 'perInquilini.autocandidatura.prova3.testo', sezione: 'L’autocandidatura', etichetta: 'Prova 3 · testo', testo: 'Il contratto di locazione registrato, con gli estremi della registrazione.' },
        { chiave: 'perInquilini.autocandidatura.nota1', sezione: 'L’autocandidatura', etichetta: 'Riquadro blu · punto 1', testo: 'Sotto il minimo il certificato riporta {storicoInsufficiente}, senza colore.' },
        { chiave: 'perInquilini.autocandidatura.nota2', sezione: 'L’autocandidatura', etichetta: 'Riquadro blu · punto 2', testo: 'Sul certificato la fonte è «{fonteDocumenti}».' },
        { chiave: 'perInquilini.autocandidatura.nota3', sezione: 'L’autocandidatura', etichetta: 'Riquadro blu · punto 3', testo: 'La referenza del precedente proprietario parte solo se la chiedi tu.' },
        { chiave: 'perInquilini.autocandidatura.pulsante', sezione: 'L’autocandidatura', etichetta: 'Riquadro blu · pulsante', testo: "Inizia l'autocandidatura" },

        { chiave: 'perInquilini.faq.occhiello', sezione: 'Domande frequenti', etichetta: 'Occhiello (le domande si cambiano da FAQ)', testo: 'Domande frequenti' },
        { chiave: 'perInquilini.faq.titolo', sezione: 'Domande frequenti', etichetta: 'Titolo', testo: 'Le domande che *ti stai facendo.*' },

        { chiave: 'perInquilini.chiusura.occhiello', sezione: 'Chiusura', etichetta: 'Occhiello', testo: 'Per iniziare' },
        { chiave: 'perInquilini.chiusura.titolo', sezione: 'Chiusura', etichetta: 'Titolo', testo: 'Il tuo proprietario *non è su CRIA?*' },
        { chiave: 'perInquilini.chiusura.testo', sezione: 'Chiusura', etichetta: 'Testo sotto il titolo', testo: "Con un contratto CRIA attivo il certificato è gratuito. Puoi fargli conoscere CRIA con questo messaggio, oppure passare dall'autocandidatura.", lungo: true },
        { chiave: 'perInquilini.chiusura.messaggio.titolo', sezione: 'Chiusura', etichetta: 'Messaggio · titolo', testo: 'Messaggio pronto da inviare' },
        { chiave: 'perInquilini.chiusura.messaggio.sottotitolo', sezione: 'Chiusura', etichetta: 'Messaggio · sotto il titolo', testo: 'Personalizzalo come preferisci' },
        { chiave: 'perInquilini.chiusura.messaggio.testo', sezione: 'Chiusura', etichetta: 'Messaggio · il testo (è anche quello che si copia e si invia)', testo: 'Ciao, ti segnalo CRIA — Centrale Rischi Immobiliare Affitti. Ogni mese registra se il canone è arrivato: io vedo il mio semaforo e, con il contratto su CRIA, posso avere il certificato gratuito. Per il proprietario ci sono prodotti con garanzia e uno senza garanzia per le sole segnalazioni, con il prezzo già nel listino. Trovi tutto qui: https://cri-affitti.it/per-proprietari', lungo: true },
        { chiave: 'perInquilini.chiusura.messaggio.oggettoEmail', sezione: 'Chiusura', etichetta: 'Messaggio · oggetto dell’email', testo: 'Ti presento CRIA' },
        { chiave: 'perInquilini.chiusura.pulsanteCopia', sezione: 'Chiusura', etichetta: 'Pulsante per copiare il messaggio', testo: 'Copia il messaggio' },
        { chiave: 'perInquilini.chiusura.pulsanteCopiato', sezione: 'Chiusura', etichetta: 'Lo stesso pulsante, appena copiato', testo: 'Copiato!' },
        { chiave: 'perInquilini.chiusura.pulsanteWhatsapp', sezione: 'Chiusura', etichetta: 'Pulsante WhatsApp', testo: 'Apri WhatsApp' },
        { chiave: 'perInquilini.chiusura.pulsanteEmail', sezione: 'Chiusura', etichetta: 'Pulsante email', testo: 'Invia per email' },
        { chiave: 'perInquilini.chiusura.pulsanteRegistrati', sezione: 'Chiusura', etichetta: 'Pulsante principale', testo: 'Crea il tuo account' },
        { chiave: 'perInquilini.chiusura.pulsanteAccedi', sezione: 'Chiusura', etichetta: 'Pulsante secondario', testo: 'Accedi' },
        { chiave: 'perInquilini.chiusura.domandaProprietario', sezione: 'Chiusura', etichetta: 'Frase in fondo', testo: 'Cosa offre CRIA a un proprietario?' },
        { chiave: 'perInquilini.chiusura.linkProprietario', sezione: 'Chiusura', etichetta: 'Link in fondo (alla pagina Per proprietari)', testo: 'Leggi la pagina dedicata' },
    ],
};
