// Testi della pagina Per proprietari (/per-proprietari) — l'admin li cambia da Admin → Testi.
// Nomi dei prodotti, prezzi, giorni e mesi non si scrivono qui: arrivano dal listino
// (data/catalogo.js) e dal semaforo (lib/semaforo.js) attraverso i segnaposto {…}.
export default {
    id: 'perProprietari',
    nome: 'Per proprietari',
    percorso: '/per-proprietari',
    ordine: 20,
    testi: [
        { chiave: 'perProprietari.meta.titolo', sezione: 'Motori di ricerca', etichetta: 'Titolo della scheda del browser', testo: 'Per proprietari — CRIA' },
        { chiave: 'perProprietari.meta.descrizione', sezione: 'Motori di ricerca', etichetta: 'Descrizione per i motori di ricerca', testo: 'Per chi affitta un immobile: quattro prodotti a listino, la segnalazione mensile, il semaforo dei tuoi inquilini e {nomeProdotto} prima di firmare.', lungo: true },

        { chiave: 'perProprietari.hero.occhiello', sezione: 'In alto', etichetta: 'Etichetta sopra il titolo', testo: 'Per proprietari' },
        { chiave: 'perProprietari.hero.titolo', sezione: 'In alto', etichetta: 'Titolo', testo: 'Il tuo affitto,\nmese per mese,\n*messo in chiaro.*' },
        { chiave: 'perProprietari.hero.sottotitolo', sezione: 'In alto', etichetta: 'Sottotitolo', testo: 'Per ogni contratto scegli un prodotto dal listino: con garanzia o solo segnalazione, incassi tu o incassa CRIA. Ogni mese una domanda, e il semaforo dei tuoi inquilini si costruisce su quello che succede davvero.', lungo: true },
        { chiave: 'perProprietari.hero.pulsanteInizia', sezione: 'In alto', etichetta: 'Pulsante principale', testo: 'Inizia ora' },
        { chiave: 'perProprietari.hero.pulsanteProdotti', sezione: 'In alto', etichetta: 'Pulsante che porta ai prodotti', testo: 'Vedi i prodotti' },

        { chiave: 'perProprietari.domanda.intestazione', sezione: 'In alto · la domanda del mese (esempio)', etichetta: 'Scritta in cima al riquadro', testo: 'la domanda del mese' },
        { chiave: 'perProprietari.domanda.scadenza', sezione: 'In alto · la domanda del mese (esempio)', etichetta: 'Riga sopra la domanda', testo: 'Canone in scadenza il giorno {giorno}' },
        { chiave: 'perProprietari.domanda.domanda', sezione: 'In alto · la domanda del mese (esempio)', etichetta: 'Domanda', testo: 'Il canone è arrivato?' },
        { chiave: 'perProprietari.domanda.immobile', sezione: 'In alto · la domanda del mese (esempio)', etichetta: 'Immobile d’esempio', testo: 'Appartamento · Via Roma 42, Milano' },
        { chiave: 'perProprietari.domanda.si', sezione: 'In alto · la domanda del mese (esempio)', etichetta: 'Risposta sì', testo: 'Sì' },
        { chiave: 'perProprietari.domanda.no', sezione: 'In alto · la domanda del mese (esempio)', etichetta: 'Risposta no', testo: 'No' },
        { chiave: 'perProprietari.domanda.solleciti', sezione: 'In alto · la domanda del mese (esempio)', etichetta: 'Titolo dell’elenco dei solleciti', testo: '{numeroSolleciti} solleciti prima che la finestra si chiuda' },
        { chiave: 'perProprietari.domanda.canaleNotifica', sezione: 'In alto · la domanda del mese (esempio)', etichetta: 'Canale 1', testo: 'Notifica' },
        { chiave: 'perProprietari.domanda.canaleEmail', sezione: 'In alto · la domanda del mese (esempio)', etichetta: 'Canale 2', testo: 'Email' },
        { chiave: 'perProprietari.domanda.canaleSms', sezione: 'In alto · la domanda del mese (esempio)', etichetta: 'Canale 3', testo: 'SMS' },
        { chiave: 'perProprietari.domanda.finestra', sezione: 'In alto · la domanda del mese (esempio)', etichetta: 'Riquadro verde · in grande', testo: '{giorni} giorni' },
        { chiave: 'perProprietari.domanda.finestraTesto', sezione: 'In alto · la domanda del mese (esempio)', etichetta: 'Riquadro verde · testo', testo: 'per segnalare il mancato pagamento con la copertura attiva' },
        { chiave: 'perProprietari.domanda.chiusura', sezione: 'In alto · la domanda del mese (esempio)', etichetta: 'Riquadro grigio · in grande', testo: 'Giorno {giorno}' },
        { chiave: 'perProprietari.domanda.chiusuraTesto', sezione: 'In alto · la domanda del mese (esempio)', etichetta: 'Riquadro grigio · testo', testo: 'il mese si chiude: senza risposta è non rilevato' },
        { chiave: 'perProprietari.domanda.prezzoOcchiello', sezione: 'In alto · la domanda del mese (esempio)', etichetta: 'Riquadro blu · occhiello', testo: 'Nessun preventivo' },
        { chiave: 'perProprietari.domanda.prezzoTesto', sezione: 'In alto · la domanda del mese (esempio)', etichetta: 'Riquadro blu · testo', testo: 'Il prezzo viene dal listino e dal canone' },

        { chiave: 'perProprietari.prodotti.occhiello', sezione: 'I prodotti', etichetta: 'Occhiello', testo: 'Il listino' },
        { chiave: 'perProprietari.prodotti.titolo', sezione: 'I prodotti', etichetta: 'Titolo (con quattro prodotti a listino)', testo: 'Quattro prodotti, *uno per ogni contratto.*' },
        { chiave: 'perProprietari.prodotti.titoloGenerico', sezione: 'I prodotti', etichetta: 'Titolo (se a listino i prodotti non sono quattro)', testo: 'I prodotti, *uno per ogni contratto.*' },
        { chiave: 'perProprietari.prodotti.intro', sezione: 'I prodotti', etichetta: 'Testo sotto il titolo', testo: 'Scegli se vuoi la garanzia e chi incassa il canone. Ogni prodotto costruisce lo storico dei tuoi inquilini.' },
        { chiave: 'perProprietari.prodotti.etichettaIncassaCria', sezione: 'I prodotti', etichetta: 'Scheda · etichetta del prodotto in cui incassa CRIA', testo: 'Incassa CRIA' },
        { chiave: 'perProprietari.prodotti.etichettaSenzaGaranzia', sezione: 'I prodotti', etichetta: 'Scheda · etichetta del prodotto senza garanzia', testo: 'Senza garanzia' },
        { chiave: 'perProprietari.prodotti.puntoGaranziaUnMese', sezione: 'I prodotti', etichetta: 'Scheda · punto garanzia (franchigia di un mese)', testo: 'Garanzia, con franchigia di {mesi} mese' },
        { chiave: 'perProprietari.prodotti.puntoGaranzia', sezione: 'I prodotti', etichetta: 'Scheda · punto garanzia (franchigia di più mesi)', testo: 'Garanzia, con franchigia di {mesi} mesi' },
        { chiave: 'perProprietari.prodotti.puntoSenzaGaranzia', sezione: 'I prodotti', etichetta: 'Scheda · punto garanzia (prodotto senza garanzia)', testo: 'Nessuna garanzia sui canoni' },
        { chiave: 'perProprietari.prodotti.puntoIncassaCria', sezione: 'I prodotti', etichetta: 'Scheda · punto incasso (incassa CRIA)', testo: 'CRIA incassa dall’inquilino e ti bonifica il canone' },
        { chiave: 'perProprietari.prodotti.puntoIncassiTu', sezione: 'I prodotti', etichetta: 'Scheda · punto incasso (incassi tu)', testo: 'Il canone lo incassi tu' },
        { chiave: 'perProprietari.prodotti.puntoNienteDaSegnalare', sezione: 'I prodotti', etichetta: 'Scheda · punto segnalazione (incassa CRIA)', testo: 'Non devi segnalare nulla' },
        { chiave: 'perProprietari.prodotti.puntoSegnaliOgniMese', sezione: 'I prodotti', etichetta: 'Scheda · punto segnalazione (incassi tu)', testo: 'Ogni mese segnali se il canone è arrivato' },
        { chiave: 'perProprietari.prodotti.puntoSemaforo', sezione: 'I prodotti', etichetta: 'Scheda · ultimo punto', testo: 'Il semaforo dell’inquilino si costruisce mese per mese' },
        { chiave: 'perProprietari.prodotti.nota1.titolo', sezione: 'I prodotti', etichetta: 'Nota 1 · titolo', testo: 'Un prodotto per contratto' },
        { chiave: 'perProprietari.prodotti.nota1.testo', sezione: 'I prodotti', etichetta: 'Nota 1 · testo', testo: 'Il prodotto sta sul contratto, non su di te: puoi avere {prodottoCompleto} su un immobile e {prodottoSegnalazione} su un altro.', lungo: true },
        { chiave: 'perProprietari.prodotti.nota2.titolo', sezione: 'I prodotti', etichetta: 'Nota 2 · titolo', testo: 'Nessun preventivo' },
        { chiave: 'perProprietari.prodotti.nota2.testo', sezione: 'I prodotti', etichetta: 'Nota 2 · testo', testo: 'Il prezzo viene dal listino e dal canone che dichiari. Lo vedi subito: non c’è niente da chiedere né da aspettare.' },
        { chiave: 'perProprietari.prodotti.nota3.titolo', sezione: 'I prodotti', etichetta: 'Nota 3 · titolo', testo: 'La franchigia' },
        { chiave: 'perProprietari.prodotti.nota3.testo', sezione: 'I prodotti', etichetta: 'Nota 3 · testo', testo: 'Sono i primi mesi del contratto in cui la garanzia non è ancora attiva.' },

        { chiave: 'perProprietari.mese.occhiello', sezione: 'Ogni mese', etichetta: 'Occhiello', testo: 'Ogni mese' },
        { chiave: 'perProprietari.mese.titolo', sezione: 'Ogni mese', etichetta: 'Titolo', testo: 'Una domanda al mese. *Due date che contano.*' },
        { chiave: 'perProprietari.mese.intro', sezione: 'Ogni mese', etichetta: 'Testo sotto il titolo', testo: 'I {giorni} giorni sono la finestra per chiedere la garanzia. Il giorno {giornoChiusura} è quando CRIA smette di aspettare: un mese che nessuno ha segnalato non diventa un pagamento inventato, resta non rilevato.', lungo: true },
        { chiave: 'perProprietari.mese.tappa1.etichetta', sezione: 'Ogni mese', etichetta: 'Tappa 1 · quando', testo: 'Giorno {giorno}' },
        { chiave: 'perProprietari.mese.tappa1.titolo', sezione: 'Ogni mese', etichetta: 'Tappa 1 · titolo', testo: 'Scade il canone' },
        { chiave: 'perProprietari.mese.tappa1.testo', sezione: 'Ogni mese', etichetta: 'Tappa 1 · testo', testo: 'Il mese parte da qui.' },
        { chiave: 'perProprietari.mese.tappa2.etichetta', sezione: 'Ogni mese', etichetta: 'Tappa 2 · quando', testo: '{numeroSolleciti} solleciti' },
        { chiave: 'perProprietari.mese.tappa2.titolo', sezione: 'Ogni mese', etichetta: 'Tappa 2 · titolo', testo: 'Te lo chiediamo noi' },
        { chiave: 'perProprietari.mese.tappa2.testo', sezione: 'Ogni mese', etichetta: 'Tappa 2 · testo', testo: '{solleciti}: con notifica, email e SMS. Una sola domanda, il canone è arrivato? Sì o no.' },
        { chiave: 'perProprietari.mese.tappa3.etichetta', sezione: 'Ogni mese', etichetta: 'Tappa 3 · quando', testo: 'Entro {giorni} giorni' },
        { chiave: 'perProprietari.mese.tappa3.titolo', sezione: 'Ogni mese', etichetta: 'Tappa 3 · titolo', testo: 'La finestra della garanzia' },
        { chiave: 'perProprietari.mese.tappa3.testo', sezione: 'Ogni mese', etichetta: 'Tappa 3 · testo', testo: 'Se il canone non è arrivato, segnalalo entro {giorni} giorni di calendario dalla scadenza: la copertura del mese è attiva e la pratica di morosità parte subito.', lungo: true },
        { chiave: 'perProprietari.mese.tappa4.etichetta', sezione: 'Ogni mese', etichetta: 'Tappa 4 · quando', testo: 'Giorno {giorno}' },
        { chiave: 'perProprietari.mese.tappa4.titolo', sezione: 'Ogni mese', etichetta: 'Tappa 4 · titolo', testo: 'Il mese si chiude' },
        { chiave: 'perProprietari.mese.tappa4.testo', sezione: 'Ogni mese', etichetta: 'Tappa 4 · testo', testo: 'Se entro il giorno {giorno} nessuno ha risposto, il mese diventa non rilevato: non conta nel semaforo e non è coperto.' },
        { chiave: 'perProprietari.mese.colonnaSegnalazione', sezione: 'Ogni mese', etichetta: 'Tabella · intestazione della colonna 1', testo: 'Cosa segnali' },
        { chiave: 'perProprietari.mese.colonnaSemaforo', sezione: 'Ogni mese', etichetta: 'Tabella · intestazione della colonna 2', testo: 'Per il semaforo dell’inquilino' },
        { chiave: 'perProprietari.mese.colonnaCopertura', sezione: 'Ogni mese', etichetta: 'Tabella · intestazione della colonna 3', testo: 'Per la tua copertura' },
        { chiave: 'perProprietari.mese.esito1.quando', sezione: 'Ogni mese', etichetta: 'Tabella · riga 1 · cosa segnali', testo: '«No» entro {giorni} giorni' },
        { chiave: 'perProprietari.mese.esito1.semaforo', sezione: 'Ogni mese', etichetta: 'Tabella · riga 1 · per il semaforo', testo: 'Conta come non pagato' },
        { chiave: 'perProprietari.mese.esito1.copertura', sezione: 'Ogni mese', etichetta: 'Tabella · riga 1 · per la copertura', testo: 'Attiva: la pratica di morosità parte subito' },
        { chiave: 'perProprietari.mese.esito2.quando', sezione: 'Ogni mese', etichetta: 'Tabella · riga 2 · cosa segnali', testo: '«No» dopo {giorni} giorni' },
        { chiave: 'perProprietari.mese.esito2.semaforo', sezione: 'Ogni mese', etichetta: 'Tabella · riga 2 · per il semaforo', testo: 'Conta comunque come non pagato: è quello che è successo' },
        { chiave: 'perProprietari.mese.esito2.copertura', sezione: 'Ogni mese', etichetta: 'Tabella · riga 2 · per la copertura', testo: 'Decade per quel mese' },
        { chiave: 'perProprietari.mese.esito3.quando', sezione: 'Ogni mese', etichetta: 'Tabella · riga 3 · cosa segnali', testo: '«Sì» entro il giorno {giorno}' },
        { chiave: 'perProprietari.mese.esito3.semaforo', sezione: 'Ogni mese', etichetta: 'Tabella · riga 3 · per il semaforo', testo: 'Entra nella media del giorno di pagamento' },
        { chiave: 'perProprietari.mese.esito3.copertura', sezione: 'Ogni mese', etichetta: 'Tabella · riga 3 · per la copertura', testo: '—' },
        { chiave: 'perProprietari.mese.esito4.quando', sezione: 'Ogni mese', etichetta: 'Tabella · riga 4 · cosa segnali', testo: 'Nessuna risposta entro il giorno {giorno}' },
        { chiave: 'perProprietari.mese.esito4.semaforo', sezione: 'Ogni mese', etichetta: 'Tabella · riga 4 · per il semaforo', testo: 'Non rilevato: pesa zero' },
        { chiave: 'perProprietari.mese.esito4.copertura', sezione: 'Ogni mese', etichetta: 'Tabella · riga 4 · per la copertura', testo: 'Non coperto' },
        { chiave: 'perProprietari.mese.notaMeseSaltato', sezione: 'Ogni mese', etichetta: 'Sotto la tabella · frase in verde', testo: 'Se salti un mese, la copertura riprende dal primo mese segnalato correttamente.' },
        { chiave: 'perProprietari.mese.notaIncassaCria', sezione: 'Ogni mese', etichetta: 'Sotto la tabella · prodotti in cui incassa CRIA', testo: '**{prodottiIncassaCria}**: incassa CRIA, quindi sa già se il canone è arrivato. Non segnali nulla.' },
        { chiave: 'perProprietari.mese.notaSenzaGaranzia', sezione: 'Ogni mese', etichetta: 'Sotto la tabella · prodotti senza garanzia', testo: '**{prodottiSenzaGaranzia}**: nessuna copertura. La tua segnalazione conta per il semaforo.' },

        { chiave: 'perProprietari.semaforo.occhiello', sezione: 'Il semaforo dei tuoi inquilini', etichetta: 'Occhiello', testo: 'Il semaforo dei tuoi inquilini' },
        { chiave: 'perProprietari.semaforo.titolo', sezione: 'Il semaforo dei tuoi inquilini', etichetta: 'Titolo', testo: 'Un colore che viene *dai pagamenti.*' },
        { chiave: 'perProprietari.semaforo.intro', sezione: 'Il semaforo dei tuoi inquilini', etichetta: 'Testo sotto il titolo', testo: 'È la media del giorno del mese in cui l’inquilino ha pagato il canone, negli ultimi {mesi} mesi. Si calcola sulla persona, su tutti i suoi contratti di affitto, non sul singolo contratto.', lungo: true },
        { chiave: 'perProprietari.semaforo.regola1', sezione: 'Il semaforo dei tuoi inquilini', etichetta: 'Regola 1', testo: 'I mesi non rilevati pesano zero, né a favore né contro.' },
        { chiave: 'perProprietari.semaforo.regola2', sezione: 'Il semaforo dei tuoi inquilini', etichetta: 'Regola 2', testo: 'Un mese contestato resta fuori finché la contestazione non si chiude.' },
        { chiave: 'perProprietari.semaforo.regola3', sezione: 'Il semaforo dei tuoi inquilini', etichetta: 'Regola 3', testo: 'Nessuno in CRIA può cambiare un semaforo a mano: lo corregge solo una contestazione istruita.' },
        { chiave: 'perProprietari.semaforo.regola4', sezione: 'Il semaforo dei tuoi inquilini', etichetta: 'Regola 4', testo: 'L’inquilino vede sempre il proprio semaforo, con la spiegazione di come è costruito.' },
        { chiave: 'perProprietari.semaforo.regola5', sezione: 'Il semaforo dei tuoi inquilini', etichetta: 'Regola 5', testo: 'Sui tuoi contratti vedi tutto: ogni mese e ogni segnalazione.' },
        { chiave: 'perProprietari.semaforo.esempio.intestazione', sezione: 'Il semaforo dei tuoi inquilini', etichetta: 'Riquadro d’esempio · scritta in cima', testo: 'semaforo · ultimi {mesi} mesi' },
        { chiave: 'perProprietari.semaforo.esempio.nonRilevato', sezione: 'Il semaforo dei tuoi inquilini', etichetta: 'Riquadro d’esempio · nota in fondo', testo: '*Non rilevato* · un mese che nessuno ha segnalato: non entra nel calcolo.' },

        { chiave: 'perProprietari.verifica.occhiello', sezione: 'Prima di firmare', etichetta: 'Occhiello', testo: 'Prima di firmare · {nomeProdotto}' },
        { chiave: 'perProprietari.verifica.titolo', sezione: 'Prima di firmare', etichetta: 'Titolo', testo: 'Hai un candidato? *Chiedi a CRIA come paga.*' },
        { chiave: 'perProprietari.verifica.intro', sezione: 'Prima di firmare', etichetta: 'Testo sotto il titolo', testo: 'Per chi sta per affittare: un’interrogazione sul candidato inquilino, a {prezzo}.' },
        { chiave: 'perProprietari.verifica.passo1.titolo', sezione: 'Prima di firmare', etichetta: 'Passo 1 · titolo', testo: 'Completa l’account' },
        { chiave: 'perProprietari.verifica.passo1.testo', sezione: 'Prima di firmare', etichetta: 'Passo 1 · testo', testo: 'Serve un account con i dati di fatturazione completati.' },
        { chiave: 'perProprietari.verifica.passo2.titolo', sezione: 'Prima di firmare', etichetta: 'Passo 2 · titolo', testo: 'Inserisci il candidato' },
        { chiave: 'perProprietari.verifica.passo2.testo', sezione: 'Prima di firmare', etichetta: 'Passo 2 · testo', testo: 'Nome, cognome, data e luogo di nascita, codice fiscale.' },
        { chiave: 'perProprietari.verifica.passo3.titolo', sezione: 'Prima di firmare', etichetta: 'Passo 3 · titolo', testo: 'Paghi {prezzo}' },
        { chiave: 'perProprietari.verifica.passo3.testo', sezione: 'Prima di firmare', etichetta: 'Passo 3 · testo', testo: 'Il prezzo è quello del listino, uguale per ogni interrogazione.' },
        { chiave: 'perProprietari.verifica.passo4.titolo', sezione: 'Prima di firmare', etichetta: 'Passo 4 · titolo', testo: 'Esito entro {ore} ore' },
        { chiave: 'perProprietari.verifica.passo4.testo', sezione: 'Prima di firmare', etichetta: 'Passo 4 · testo', testo: 'Ti arriva un’email che ti invita ad accedere: l’esito si legge dentro la piattaforma. Nessun PDF, nessun allegato.' },
        { chiave: 'perProprietari.verifica.pulsante', sezione: 'Prima di firmare', etichetta: 'Testo del pulsante', testo: 'Scopri {nomeProdotto}' },
        { chiave: 'perProprietari.verifica.esito.titolo', sezione: 'Prima di firmare', etichetta: 'Riquadro blu · titolo', testo: 'Cosa vedi nell’esito' },
        { chiave: 'perProprietari.verifica.esito.semaforo', sezione: 'Prima di firmare', etichetta: 'Riquadro blu · voce «Semaforo»', testo: 'Semaforo' },
        { chiave: 'perProprietari.verifica.esito.sintesi', sezione: 'Prima di firmare', etichetta: 'Riquadro blu · voce «Sintesi»', testo: 'Sintesi' },
        { chiave: 'perProprietari.verifica.esito.oppure', sezione: 'Prima di firmare', etichetta: 'Riquadro blu · l’altro esito possibile', testo: 'oppure «non abbiamo informazioni in merito»' },
        { chiave: 'perProprietari.verifica.esito.scalabile', sezione: 'Prima di firmare', etichetta: 'Riquadro blu · il prezzo si scala', testo: 'I {prezzo} si scalano dal primo prodotto che acquisti entro {giorni} giorni' },
        { chiave: 'perProprietari.verifica.esito.scalabileNota', sezione: 'Prima di firmare', etichetta: 'Riquadro blu · nota sotto', testo: 'Sullo stesso account, un’interrogazione per acquisto.' },
        { chiave: 'perProprietari.verifica.esito.piede', sezione: 'Prima di firmare', etichetta: 'Riquadro blu · riga in fondo', testo: 'Sull’interrogazione vedi solo semaforo e sintesi. Quando il contratto è tuo, vedi tutto.' },

        { chiave: 'perProprietari.nonArriva.occhiello', sezione: 'Se il canone non arriva', etichetta: 'Occhiello', testo: 'Se il canone non arriva' },
        { chiave: 'perProprietari.nonArriva.titolo', sezione: 'Se il canone non arriva', etichetta: 'Titolo', testo: 'Non coperto *non vuol dire non gestito.*' },
        { chiave: 'perProprietari.nonArriva.caso1.titolo', sezione: 'Se il canone non arriva', etichetta: 'Caso 1 · titolo', testo: 'Segnali il mancato pagamento' },
        { chiave: 'perProprietari.nonArriva.caso1.testo', sezione: 'Se il canone non arriva', etichetta: 'Caso 1 · testo', testo: 'Rispondi «no» entro {giorni} giorni di calendario dalla scadenza.' },
        { chiave: 'perProprietari.nonArriva.caso1.esito', sezione: 'Se il canone non arriva', etichetta: 'Caso 1 · riquadro', testo: 'La copertura del mese è attiva e la pratica di morosità parte subito.' },
        { chiave: 'perProprietari.nonArriva.caso2.titolo', sezione: 'Se il canone non arriva', etichetta: 'Caso 2 · titolo', testo: 'La pratica si apre comunque' },
        { chiave: 'perProprietari.nonArriva.caso2.testo', sezione: 'Se il canone non arriva', etichetta: 'Caso 2 · testo', testo: 'Anche se hai segnalato tardi, o il mese non era coperto, la pratica di morosità si apre lo stesso.' },
        { chiave: 'perProprietari.nonArriva.caso2.esito', sezione: 'Se il canone non arriva', etichetta: 'Caso 2 · riquadro', testo: 'Il recupero parte: un piano di rientro con l’inquilino e, se serve, l’avvocato.' },
        { chiave: 'perProprietari.nonArriva.caso3.titolo', sezione: 'Se il canone non arriva', etichetta: 'Caso 3 · titolo', testo: 'Con la garanzia, CRIA ti indennizza' },
        { chiave: 'perProprietari.nonArriva.caso3.testo', sezione: 'Se il canone non arriva', etichetta: 'Caso 3 · testo', testo: 'Con {prodottiConGaranzia}, per i mesi coperti CRIA indennizza il proprietario.' },
        { chiave: 'perProprietari.nonArriva.caso3.esito', sezione: 'Se il canone non arriva', etichetta: 'Caso 3 · riquadro', testo: 'Con {prodottiSenzaGaranzia} non c’è garanzia: il mese non pagato entra nel semaforo dell’inquilino.' },
        { chiave: 'perProprietari.nonArriva.incassaCria', sezione: 'Se il canone non arriva', etichetta: 'Frase in fondo', testo: 'Con **{prodottiIncassaCria}** il canone lo incassa CRIA: se non arriva lo sa già, e tu non devi segnalare nulla.' },

        { chiave: 'perProprietari.contestazione.occhiello', sezione: 'Se l’inquilino contesta', etichetta: 'Occhiello', testo: 'Se l’inquilino contesta' },
        { chiave: 'perProprietari.contestazione.titolo', sezione: 'Se l’inquilino contesta', etichetta: 'Titolo', testo: 'Una segnalazione si contesta *solo con una prova.*' },
        { chiave: 'perProprietari.contestazione.intro', sezione: 'Se l’inquilino contesta', etichetta: 'Testo sotto il titolo', testo: 'La contestazione serve a correggere un errore, ed è l’unico modo per cambiare un semaforo. Dal tuo lato funziona così.' },
        { chiave: 'perProprietari.contestazione.regola1.titolo', sezione: 'Se l’inquilino contesta', etichetta: 'Scheda 1 · titolo', testo: 'Chi può contestare' },
        { chiave: 'perProprietari.contestazione.regola1.testo', sezione: 'Se l’inquilino contesta', etichetta: 'Scheda 1 · testo', testo: 'Solo l’inquilino, e solo una segnalazione di mancato pagamento.' },
        { chiave: 'perProprietari.contestazione.regola2.titolo', sezione: 'Se l’inquilino contesta', etichetta: 'Scheda 2 · titolo', testo: 'Entro quando' },
        { chiave: 'perProprietari.contestazione.regola2.testo', sezione: 'Se l’inquilino contesta', etichetta: 'Scheda 2 · testo', testo: 'Entro {giorni} giorni dalla tua segnalazione.' },
        { chiave: 'perProprietari.contestazione.regola3.titolo', sezione: 'Se l’inquilino contesta', etichetta: 'Scheda 3 · titolo', testo: 'Con cosa' },
        { chiave: 'perProprietari.contestazione.regola3.testo', sezione: 'Se l’inquilino contesta', etichetta: 'Scheda 3 · testo', testo: 'Con una prova, per esempio la ricevuta di un bonifico. CRIA guarda le prove di entrambe le parti.' },
        { chiave: 'perProprietari.contestazione.regola4.titolo', sezione: 'Se l’inquilino contesta', etichetta: 'Scheda 4 · titolo', testo: 'L’esito' },
        { chiave: 'perProprietari.contestazione.regola4.testo', sezione: 'Se l’inquilino contesta', etichetta: 'Scheda 4 · testo', testo: 'CRIA decide e risponde entro {giorni} giorni. Finché la contestazione è aperta, quel mese non conta nel semaforo.' },

        { chiave: 'perProprietari.inizio.occhiello', sezione: 'Come si inizia', etichetta: 'Occhiello', testo: 'Come si inizia' },
        { chiave: 'perProprietari.inizio.titolo', sezione: 'Come si inizia', etichetta: 'Titolo', testo: 'Dalla registrazione *al contratto firmato.*' },
        { chiave: 'perProprietari.inizio.agenzia.titolo', sezione: 'Come si inizia', etichetta: 'Riquadro agenzie · titolo', testo: 'Sei un’agenzia immobiliare?' },
        { chiave: 'perProprietari.inizio.agenzia.testo', sezione: 'Come si inizia', etichetta: 'Riquadro agenzie · testo', testo: 'C’è {nomeProdotto}. {prezzo}.' },
        { chiave: 'perProprietari.inizio.agenzia.link', sezione: 'Come si inizia', etichetta: 'Riquadro agenzie · link', testo: 'Contattaci' },
        { chiave: 'perProprietari.inizio.passo1.titolo', sezione: 'Come si inizia', etichetta: 'Passo 1 · titolo', testo: 'Registrati' },
        { chiave: 'perProprietari.inizio.passo1.testo', sezione: 'Come si inizia', etichetta: 'Passo 1 · testo', testo: 'Come persona fisica o come società. Puoi entrare anche con Google.' },
        { chiave: 'perProprietari.inizio.passo2.titolo', sezione: 'Come si inizia', etichetta: 'Passo 2 · titolo', testo: 'Verifichiamo la tua identità' },
        { chiave: 'perProprietari.inizio.passo2.testo', sezione: 'Come si inizia', etichetta: 'Passo 2 · testo', testo: 'Carichi un documento d’identità e lo controlla una persona di CRIA, anche se sei entrato con Google.' },
        { chiave: 'perProprietari.inizio.passo3.titolo', sezione: 'Come si inizia', etichetta: 'Passo 3 · titolo', testo: 'Un account, più ruoli' },
        { chiave: 'perProprietari.inizio.passo3.testo', sezione: 'Come si inizia', etichetta: 'Passo 3 · testo', testo: 'Se sei proprietario e anche inquilino non ti serve un secondo account: passi da «come proprietario» a «come inquilino» dal selettore del contesto.', lungo: true },
        { chiave: 'perProprietari.inizio.passo4.titolo', sezione: 'Come si inizia', etichetta: 'Passo 4 · titolo', testo: 'Scegli il prodotto per ogni contratto' },
        { chiave: 'perProprietari.inizio.passo4.testo', sezione: 'Come si inizia', etichetta: 'Passo 4 · testo', testo: 'Dal listino, sul canone che dichiari. Il prezzo lo vedi subito.' },
        { chiave: 'perProprietari.inizio.passo5.titolo', sezione: 'Come si inizia', etichetta: 'Passo 5 · titolo', testo: 'Ognuno carica i propri documenti' },
        { chiave: 'perProprietari.inizio.passo5.testo', sezione: 'Come si inizia', etichetta: 'Passo 5 · testo', testo: 'Il candidato inquilino carica i suoi da un link personale, con informativa e consenso: tu vedi quali documenti mancano, non i documenti. Dei documenti bancari servono solo i movimenti del canone degli ultimi {mesi} mesi, non l’estratto conto intero.', lungo: true },
        { chiave: 'perProprietari.inizio.passo6.titolo', sezione: 'Come si inizia', etichetta: 'Passo 6 · titolo', testo: 'Firmi dentro la piattaforma' },
        { chiave: 'perProprietari.inizio.passo6.testo', sezione: 'Come si inizia', etichetta: 'Passo 6 · testo', testo: 'Il contratto si firma elettronicamente su CRIA. CRIA non registra il contratto: ne riceve gli estremi di registrazione.' },

        { chiave: 'perProprietari.chiusura.occhiello', sezione: 'Chiusura', etichetta: 'Occhiello', testo: 'Per iniziare' },
        { chiave: 'perProprietari.chiusura.titolo', sezione: 'Chiusura', etichetta: 'Titolo', testo: 'Parti dal primo contratto. *Il resto viene mese per mese.*' },
        { chiave: 'perProprietari.chiusura.testo', sezione: 'Chiusura', etichetta: 'Testo sotto il titolo', testo: 'Registrati, fai verificare la tua identità e scegli il prodotto dal listino. Se stai ancora scegliendo l’inquilino, parti da {nomeProdotto}.', lungo: true },
        { chiave: 'perProprietari.chiusura.pulsanteRegistrati', sezione: 'Chiusura', etichetta: 'Pulsante principale', testo: 'Registrati' },
        { chiave: 'perProprietari.chiusura.pulsanteVerifica', sezione: 'Chiusura', etichetta: 'Pulsante secondario', testo: 'Verifica un candidato' },
        { chiave: 'perProprietari.chiusura.linkDomande', sezione: 'Chiusura', etichetta: 'Link al supporto', testo: 'Hai domande? Scrivici' },
    ],
};
